(function(c){var a=window.AmazonUIPageJS||window.P,d=a._namespace||a.attributeErrors,b=d?d("NpxBuyNowAssets@Shared","NpxBuyNowAssets"):a;b.guardFatal?b.guardFatal(c)(b,window):b.execute(function(){c(b,window)})})(function(c,a,d){"use strict";c.when("ready").register("npx-buynow-csm",function(){return{logCount:function(b){a.ue&&a.ue.count&&a.ue.count(b,1)}}})});
/* ******** */
(function(b){var c=window.AmazonUIPageJS||window.P,d=c._namespace||c.attributeErrors,a=d?d("NpxBuyNowAssets@Desktop","NpxBuyNowAssets"):c;a.guardFatal?a.guardFatal(b)(a,window):a.execute(function(){b(a,window)})})(function(b,c,d){"use strict";b.when("A","npx-buynow-csm","ready").register("npx-buynow-education-desktop-logger",function(a,b){a.on("a:popover:show:buynow-education-popover",function(){b.logCount("desktopBuyNowEducationPopoverShow")})})});
/* ******** */
(function(k){var m=window.AmazonUIPageJS||window.P,y=m._namespace||m.attributeErrors,d=y?y("TurboCheckoutBaseAssets",""):m;d.guardFatal?d.guardFatal(k)(d,window):d.execute(function(){k(d,window)})})(function(k,m,y){"use strict";k.register("turbo-function-adapter",function(){return{adapt:function(d){return function(){if("function"!==typeof d)throw"Parameter 'property' is invalid. Expected a function but got "+typeof d;return d.apply(d,arguments)}}}});"use strict";k.when("turbo-configuration","turbo-function-adapter").execute("turbo-signin-adapter-factory",
function(d,c){k.when(d.get(d.KEYS.SHOW_SIGN_IN_INTERFACE)).register("turbo-signin-adapter",function(a){return{show:c.adapt(a.show)}})});"use strict";k.when("turbo-configuration","turbo-function-adapter").execute("turbo-view-adapter-factory",function(d,c){k.when(d.get(d.KEYS.VIEW_ADAPTER)).register("turbo-view-adapter",function(a){return{registerCallbacks:c.adapt(a.registerCallbacks),close:c.adapt(a.close),show:c.adapt(a.show),removeContent:c.adapt(a.removeContent),setContent:c.adapt(a.setContent),
closeImmediatelyThenExecute:c.adapt(a.closeImmediatelyThenExecute),closeAndNavigate:c.adapt(a.closeAndNavigate),closeToFullscreen:c.adapt(a.closeToFullscreen),updateBounds:c.adapt(a.updateBounds)}})});"use strict";k.when("turbo-checkout-page-ready").execute(function(){k.declare("turbo-eligibility-override",!1)});"use strict";k.when("A","turbo-checkout-csm","turbo-configuration","turbo-checkout-page-ready").register("turbo-checkout-address-id",function(d,c,a){function b(a){for(var b=0;b<a.length;b++){var d=
e(a[b]);if(0<d.length)return c.logCount("turboCheckoutAddressSelectorIndex"+b),d}c.logCount("turboCheckoutAddressSelectorMissing");return e()}var e=d.$;return{getAddressId:function(){return b(a.get(a.KEYS.ADDRESS_INPUT_SELECTORS)).val()||""},set:function(c){b(a.get(a.KEYS.ADDRESS_INPUT_SELECTORS)).val()!==c&&b(a.get(a.KEYS.ADDRESS_INPUT_SELECTORS)).val(c).trigger("change",[c])}}});"use strict";k.when("A","turbo-checkout-utils","turbo-callback-list","turbo-configuration","turbo-checkout-load-events",
"turbo-checkout-page-ready").register("turbo-checkbox-exclusion-listener",function(d,c,a,b,e){function f(a){var c=q;q=!1;for(var b=0;b<l.length;b++){var d=t(l[b]).find("input[type\x3dcheckbox]");a(d)}c!==q&&(n("Exclusion checkbox state changed"),p.callAll("exclusionCheckbox"))}function h(a){var c;if(!(c=q)){c=!1;for(var b=0;b<a.length&&!c;b++){var d=t(a[b]);(c=d.prop("checked"))&&n("Exclusion checkbox is checked",d)}}q=c}function n(a,b){c.logDebug("turbo-checkbox-exclusion-listener",a,b)}function g(){f(h)}
var l=b.get(b.KEYS.CHECKBOX_EXCLUSION_ROOT_NODES),t=d.$,p=a.create(),q=!1;e.bind(function(){f(function(a){n("Listening for change events on:",a);a.unbind("change",g).bind("change",g);h(a)})});return{onStateChange:function(a){p.push(a)},isAnyCheckboxChecked:function(){return q}}});"use strict";k.when("A","turbo-callback-list","turbo-checkout-load-events","turbo-checkout-page-ready").register("turbo-checkout-custom-price-input",function(d,c,a){function b(){var a=e();n!==a&&(n=a,h.callAll())}function e(){return f("#gcPriceOverride").val()||
""}var f=d.$,h=c.create(),n;a.bind(function(){n=e();f("#gcPriceOverride").unbind("change",b).bind("change",b)});return{getCustomPrice:e,onChange:function(a){h.push(a)}}});"use strict";k.when("A","turbo-checkout-csm","turbo-checkout-utils","turbo-configuration","turbo-callback-list","turbo-checkout-load-events","turbo-checkout-page-ready").register("turbo-checkout-quantity-input",function(d,c,a,b,e,f){function h(c){var b;b=c?c.value?parseInt(c.value,10):c.target&&c.target.value?parseInt(c.target.value,
10):void 0:void 0;q===b?a.logDebug("turbo-checkout-quantity-input","Quantity change event does NOT have new quantity. Suppressing callbacks",void 0):(q=b,a.logDebug("turbo-checkout-quantity-input","Quantity change event",c),l.callAll())}function n(a){a=a.val();(a=parseInt(a,10))||c.logCount("turboCheckoutNoQuantityFromPage");return a}var g=d.$,l=e.create(),t=b.get(b.KEYS.QUANTITY_SELECT_SELECTOR),p="Multiple quantity nodes present on the page. This may lead to an incorrect quantity being used in Turbo! Selector \x3d "+
t,q;f.bind(function(){var b=g(t);q=n(b);b.unbind("change",h).bind("change",h);1<b.length&&(a.logError(p,"turbo-checkout-quantity-input"),a.logDebug("turbo-checkout-quantity-input",p,b));c.logCount("turboCheckoutQuantityNodes",b.length)});return{getQuantity:function(){return n(g(t))},setQuantity:function(a){var c=g(t),b=n(c);a=parseInt(a,10);b!==a&&c.val(a).change()},onChange:function(a){l.push(a)}}});"use strict";k.when("A","turbo-checkout-csm","turbo-checkout-utils","turbo-callback-list","turbo-configuration",
"turbo-checkout-quantity-input","turbo-checkout-load-events","turbo-checkout-page-ready").register("turbo-checkout-warranty-input",function(d,c,a,b,e,f,h){var n=d.$,g=b.create(),l=e.get(e.KEYS.WARRANTY_CHECKBOX_INPUT_SELECTOR),t=e.get(e.KEYS.WARRANTY_CHECKBOX_RELATIVE_PARENT_SELECTOR),p=e.get(e.KEYS.WARRANTY_ASIN_INPUT_NAME),q=e.get(e.KEYS.WARRANTY_OFFER_INPUT_SELECTOR);h.bind(function(){n(l).unbind("click",g.callAll).bind("click",g.callAll)});return{select:function(a){a&&n(t+" input[name^\x3d"+p+
"][value\x3d"+a+"]").parents(t).find(l).click()},onChange:function(a){g.push(a)},getLineItem:function(b){if(n(l+":checked").length){var d=n(l+":checked").first().parents(t).find("input[name^\x3d"+p+"]").val()||"",e=n(q).val()||"";b=parseInt(b,10)||f.getQuantity()||1;if(d&&e)return{asin:d,offerListingId:e,quantity:b,isDiscoveredAsin:!0};c.logCount("turboCheckoutIncompleteWarrantyInputs");a.logError("Incomplete input data for the selected warranty checkbox - asin:"+d+", offerId:"+e+", quantity:"+b)}else a.logDebug("turbo-checkout-warranty-input",
"No warranty checkbox is selected",void 0)}}});"use strict";k.when("A","turbo-checkout-csm","turbo-callback-list","turbo-configuration","turbo-checkout-load-events","turbo-checkout-page-ready").register("turbo-checkout-vas-input",function(d,c,a,b,e){function f(){return l(n).prop("checked")||!1}function h(){var a=p;p=f();a!==p&&t.callAll(p)}var n=b.get(b.KEYS.VAS_CHECKBOX_SELCTOR),g=b.get(b.KEYS.VAS_CHANGE_EVENTS),l=d.$,t=a.create(),p;e.bind(function(){p=f();g.forEach(function(a){d.off(a,h);d.on(a,
h)})});return{isSelected:f,onChange:function(a){t.push(a)}}});"use strict";k.when("A","turbo-checkout-utils","turbo-callback-list","turbo-checkout-load-events","turbo-checkout-csm","turbo-checkout-aui-page-state-parser","turbo-configuration","turbo-checkout-page-ready").register("turbo-checkout-accessories-input",function(d,c,a,b,e,f,h){function n(){var a=r;r=z();r!==a&&u.callAll()}function g(){if(k===y&&w(v).length){var a=f.parse("simpleBundleParameterMap",".simpleBundleFeatureContainer");0===a.length?
(e.logCount("Turbo:Accessories:No:State"),k={}):l(a)}}function l(a){k={};a[0].items.forEach(function(a){k[a.asin]={asin:a.asin,offerListingId:a.offerListingId,isDiscoveredAsin:!0}})}function t(){return w(v).find("input[type\x3dcheckbox]")}function p(){t().unbind("change",n).bind("change",n)}function q(){return w(v).length?1>=r:0===r}function z(){var a=0;t().each(function(){w(this).prop("checked")&&a++});c.logDebug("turbo-checkout-accessories-input","Accessories selected "+a);return a}var w=d.$,u=
a.create(),r=0,k,v=h.get(h.KEYS.ENABLED_ACCESSORIES_SELECTOR);g();p();b.bind(function(){g();p();z()});return{isEligible:q,registerCallback:function(a){u.push(a)},getLineItem:function(){if(q()){var a;a=t().filter(":checked").val();a=k?k[a]:void 0;return a||y}return y},select:function(a){a&&w(v+" input[type\x3dcheckbox][value\x3d"+a+"]").click()}}});"use strict";k.when("A","turbo-checkout-csm","turbo-checkout-utils","turbo-checkout-form","turbo-checkout-ref-tagger","turbo-checkout-page-state","turbo-checkout-product-state",
"turbo-checkout-page-ready").register("turbo-checkout-joined-state",function(d,c,a,b,e,f,h){function n(a,c,b){c&&(b&&(c.quantity=b),a.push(c))}function g(a,p){function f(){var b=a.turboWeblab;b||c.logCount("turboCheckoutWeblabNameNotDefinedInState");return b}function h(){return a.turboWeblabTreatment}this.pageState=a;this.productStates=p;this.getLineItems=function(){return g.lineItemInputs};this.getActiveId=function(){return g.id};this.getHeaderText=function(){return g?g.turboHeaderText||a.turboHeaderText:
a.turboHeaderText};this.getLoadingText=function(){return a.turboLoadingText};this.getAddressId=function(){return a.addressId};this.getRequestId=function(){return a.requestId};this.getSessionId=function(){return a.sessionId};this.getInitiateSelector=function(){return a.initiateSelector};this.getWeblab=f;this.getWeblabTreatment=h;this.isTurboLaunched=function(){return!f()&&"C"!==h()};this.isProductStateEligible=function(){return p.isTurboEligible};this.getRefTag=function(){if(!g)throw"Turbo checkout product state is NOT resolved. Cannot generate ref tag";
var a=d.$("#"+g.id),a=b.getRefTag(a);return e.generateJoinedValue(a)};this.resolve=function(a){if(a){g=p.states[a];if(!g)throw a="Resolved turbo checkout product state is undefined. Id \x3d "+a,l(a,p),a;l("Resolved new product state",g);d.trigger("turbo:checkout:state:product:resolved")}};var g=1!==p.states.length?y:p.states[0]}function l(c,b){a.logDebug("turbo-checkout-joined-state",c,b)}return{createTurboState:function(a,b,d,e,w,u){if(e&&d)throw"Custom item price is NOT supported with warranty";
var l=f.get();b&&(l.addressId=b);b=h.get();if(a||e||d||u)a=parseInt(a,10),b.states.forEach(function(b){b.lineItemInputs.forEach(function(b){a&&(b.quantity=a);e?(b.customItemPrice=e,c.logCount("turboCheckoutItemPriceOverrided")):b.customItemPrice&&c.logCount("turboCheckoutItemPriceSelectorFallBackToTurboState")});n(b.lineItemInputs,u,a);n(b.lineItemInputs,d,a)});l=new g(l,b);l.resolve(w);return l}}});"use strict";k.when("A","turbo-checkout-csm","turbo-checkout-utils","turbo-configuration","turbo-checkout-aui-page-state-parser",
"turbo-checkout-page-ready").register("turbo-checkout-page-state",function(d,c,a,b,e){function f(a,c,b,d,e,f,h,g,n){this.version=a;this.turboWeblab=c;this.turboWeblabTreatment=b;this.initiateSelector=d;this.turboLoadingText=e;this.turboHeaderText=f;this.addressId=h;this.requestId=g;this.sessionId=n}function h(c,b){a.logDebug("turbo-checkout-page-state",c,b)}var n=b.get(b.KEYS.TURBO_PAGE_STATE_KEY),g=b.get(b.KEYS.PAGE_STATE_PARSING_ROOT_NODE_SELECTOR),l=new f("0","","C","#buy-now-button","","","",
"","");return{get:function(b,d){b=b||n;d=d||g;d=e.parse(b,d);c.logCount("turboCheckoutPageStates",d.length);1<d.length?(a.logError("Multiple turbo checkout page states found! Turbo will NOT show","turbo-checkout-page-state",void 0),h("PageStates",d),b=void 0):(0===d.length&&h("Turbo checkout page state ["+b+"] is NOT present"),b=d[0]);if(b)if(b.version)b=new f(b.version,b.turboWeblab||"",b.turboWeblabTreatment||"C",b.initiateSelector||".buy-now-button",b.turboLoadingText||"",b.turboHeaderText||"",
b.addressId||"",b.requestId||"",b.sessionId||"");else{d=b.inputs||{};var q=b.strings||{};b=new f("1",b.turboWeblab||"",b.turboWeblabTreatment||"C",(b.configurations||{}).initiateSelector||"#buy-now-button",q.TURBO_LOADING_TEXT||"",q.TURBO_CHECKOUT_HEADER||"",d.addressId||"",d.requestId||"",d.sessionId||"")}else c.logCount("turboCheckoutStateNotDefined"),b=l;h("Turbo Checkout PageState",b);return b}}});"use strict";k.when("A","turbo-checkout-csm","turbo-checkout-utils","turbo-configuration","turbo-checkout-aui-page-state-parser",
"turbo-checkout-page-ready").register("turbo-checkout-product-state",function(d,c,a,b,e){function f(a,b){this.isTurboEligible=a;this.states=b}function h(a,b,c,d){this.id=a;this.isTurboEligible=b;this.lineItemInputs=c;this.turboHeaderText=d||""}function n(a,b,c,d,e,f,h,g,p){this.asin=b||"";this.offerListingId=c||"";this.quantity=parseInt(d,10)||1;this.isTurboEligible=!!this.asin&&!!this.offerListingId&&a;this.productTitle=e||"";this.customItemPrice=f||"";this.addToCartTimeAsUnixEpochMilliseconds=h||
"";this.addToCartSessionId=g||"";this.isDiscoveredAsin=!!p}function g(b,c){a.logDebug("turbo-checkout-product-state",b,c)}function l(a){if(!a.lineItemInputs||!a.lineItemInputs.length||!a.id)return g('Versioned product state is invalid. Expected non empty "id" and "lineItemInputs". Turbo may NOT show',a),q;var b=!0,c=d.map(a.lineItemInputs,function(a){a=new n(a.isTurboEligible,a.asin,a.offerListingId,a.quantity,a.productTitle,a.customItemPrice,a.addToCartTimeAsUnixEpochMilliseconds,a.addToCartSessionId,
a.isDiscoveredAsin);b=b&&a.isTurboEligible;return a});return new h(a.id,b,c,a.turboHeaderText)}var t=b.get(b.KEYS.TURBO_PRODUCT_STATE_KEY),p=b.get(b.KEYS.PRODUCT_STATE_PARSING_ROOT_NODE_SELECTOR),q=new h("buy-now-button",!1,[],""),z=new f(!1,[q]);return{get:function(b,d){b=b||t;d=d||p;d=e.parse(b,d);c.logCount("turboCheckoutProductStates",d.length);1<d.length&&"turbo-checkout-page-state"===b?(a.logError("turbo-checkout-page-state only supports the single item use case! Turbo will NOT show","turbo-checkout-product-state",
void 0),b=[]):b=d;if((d=b)&&d.length){var r=!1;b=[];for(var k=0;k<d.length;k++){var v;var m=d[k];m?m.version?v=l(m):m.inputs&&m.eligibility?(v=m.strings||{},m=new n(m.eligibility.isEligible,m.inputs.a,m.inputs.oid,m.inputs.quantity,v.TURBO_CHECKOUT_HEADER,m.inputs.customItemPrice),v=new h("buy-now-button",m.isTurboEligible,[m],v.TURBO_CHECKOUT_HEADER)):(g('Legacy product state is missing "inputs" or "eligibility". Turbo will NOT show',m),v=q):(g("Product state parsed DOM object is invalid. Turbo may NOT show",
m),v=q);r=r||v.isTurboEligible||!1;m=v.id;if(b[m])throw d="Duplicate product state found. id \x3d "+m,g(d,b),d;b.push(v);b[v.id]=v}b=new f(r,b)}else g("Parsed states are invalid. Turbo will NOT show",d),b=z;g("Turbo Checkout Product State(s)",b);return b}}});"use strict";k.when("A","turbo-configuration","turbo-checkout-csm","turbo-checkout-utils","turbo-checkout-auto-open","turbo-checkout-address-id","turbo-checkout-quantity-input","turbo-checkout-warranty-input","turbo-checkout-custom-price-input",
"turbo-callback-list","turbo-checkout-joined-state","turbo-checkout-accessories-input","turbo-checkout-page-ready").register("turbo-checkout-state-handler",function(d,c,a,b,e,f,h,n,g,l,t,p){function q(a,b,c,d,e,q){a=a||h.getQuantity();b=b||f.getAddressId();c=c||n.getLineItem(a);d=d||g.getCustomPrice();q=q||p.getLineItem();return t.createTurboState(a,b,c,d,e,q)}function z(a,c){b.logDebug("turbo-checkout-state-handler",a,c)}function k(a,b,c,d,e){x=q(a,b,c,y,d,e)}function u(){d.trigger("turbo:checkout:product:onChange");
D.callAll()}function r(){var a=q();b.isDeepEquals(x,a)||(x=a,z("New Turbo State",x),u())}var m=d.$,v=c.get(c.KEYS.AJAX_PAGE_UPDATE_EVENT),D=l.create(),x,B=!1;x=q();return{isProductTurboEligible:function(){return!B&&x.isProductStateEligible()||c.get(c.KEYS.OVERRIDE_ELIGIBILITY)},getLineItems:function(){return x.getLineItems()},getAddressId:function(){return x.getAddressId()},getWeblabAllocation:function(){return x.getWeblabTreatment()},registerCallback:function(a){D.push(a)},startMonitoringPage:function(){e.updateInputsAndThen(k);
h.onChange(r);n.onChange(r);g.onChange(r);p.registerCallback(r);d.off(v,r);d.on(v,r);u()},getRequestId:function(){return x.getRequestId()},getSessionId:function(){return x.getSessionId()},getExperimentName:function(){return x.getWeblab()},getStrings:function(){return{TURBO_LOADING_TEXT:x.getLoadingText(),TURBO_CHECKOUT_HEADER:x.getHeaderText()}},getInitiateSelector:function(){return x.getInitiateSelector()},isTurboLaunched:function(){return x.isTurboLaunched()},isPhysicalGiftCardExperimentEligible:function(){var b=
0!==m("#giftcardcustomtwister_feature_div").length;b&&(z("Physical Gift Card use case"),a.logCount("turboCheckoutGiftCardUseCase"));return b},setTurboStateNotEligible:function(){B=!0},resolveProductState:function(a){x.resolve(a)},getActiveId:function(){return x.getActiveId()},getRefTag:function(){return x.getRefTag()}}});"use strict";k.when("A","turbo-checkout-utils","turbo-checkout-page-ready").register("turbo-checkout-aui-page-state-parser",function(d,c){var a=d.$;return{parse:function(b,d){b="script[data-a-state*\x3d'"+
b+"'], #"+b;d=d?a(d).find(b):a(b);b=[];for(var f=0;f<d.length;f++){var h;a:{try{var n=a(d[f]).text();h=JSON.parse(n);break a}catch(g){c.logError("JSON::parse exception. Exception \x3d "+g,"turbo-checkout-aui-page-state-parser",void 0)}h=void 0}h&&b.push(h)}return b}}});"use strict";k.when("jQuery","turbo-checkout-auto-open","turbo-checkout-page-ready").register("turbo-checkout-page-load-spinner",function(d,c){function a(){0!==d("#turbo-checkout-auto-load-spinner-container").length&&(d("#turbo-checkout-auto-load-spinner-container").remove(),
e.unbind("touchmove touchstart touchend touchcancel click scroll",b))}function b(a){a.preventDefault();a.stopPropagation()}var e=d("body");c.isAutoOpenEligible()&&(e.bind("touchmove touchstart touchend touchcancel click scroll",b),e.append("\x3cdiv id\x3d'turbo-checkout-auto-load-spinner-container' class\x3d'turbo-checkout-auto-load-spinner-container'\x3e\x3cdiv id\x3d'turbo-checkout-auto-load-circle-container' class\x3d'turbo-checkout-auto-load-circle-container'\x3e\x3cdiv id\x3d'turbo-checkout-auto-load-spinner' class\x3d'a-spinner a-spinner-medium turbo-checkout-auto-load-spinner'\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e"),
setTimeout(a,5E3));return{removePageLoadSpinner:a}});"use strict";k.when("turbo-configuration","turbo-checkout-ref-tagger","turbo-checkout-utils","turbo-checkout-page-ready").register("turbo-checkout-urls",function(d,c,a){function b(a,b){var c=d.get(d.KEYS.DEVICE_OVERRIDE);return"\x26pipelineType\x3dturbo\x26clientId\x3dretailwebsite"+(c?"\x26devicestring-override\x3d"+c:"")+n(a,b)}function e(a){var b=d.get(d.KEYS.HOST_PAGE_TYPE_IDENTIFIER);return"ref_\x3d"+a+"\x26referrer\x3d"+b}function f(b){return a.isNonEmptyString(b)?
"\x26weblab\x3d"+b:""}function h(){return d.get(d.KEYS.IS_ADD_TO_CART_ENABLED)?"\x26temporaryAddToCart\x3d1":""}function n(b,c){var d="";a.isNonEmptyString(b)&&(d+="\x26pageRequestId\x3d"+b);a.isNonEmptyString(c)&&(d+="\x26pageSessionId\x3d"+c);return d}function g(){return l("auiDebug","auiDebug")+l("ds_user","ds_user")+l("ds_turbo_workspace","ds_workspace")+l("stringDebug","stringDebug")}function l(b,c){var d="";b=a.getUrlQueryParam(b);a.isNonEmptyString(b)&&(d="\x26"+c+"\x3d"+b);return d}return{buildInitiatePathWith:function(a,
c,d,n){return"/checkout/turbo-initiate?"+e(a)+b(d,n)+f(c)+h()+g()},buildEligibilityPathWith:function(a,c,d,n){return"/checkout/turbo-initiate?"+e(a)+b(d,n)+f(c)+"\x26checkEligibilityOnly\x3dtrue"+h()+g()},buildConfirmPathWith:function(a,c,d,g){return"/checkout/turbo-initiate/confirm?"+e(a)+b(d,g)+f(c)+h()},buildLogPageHitPathWith:function(a,d){return"/checkout/log-page-hit?"+c.generateRefTag(a,c.ACTIONS.CLOSE,d)+b()},buildTriggerWeblabPathWith:function(a,b,c,d,g){return"/checkout/triggerWeblab?"+
e(a)+f(b)+"\x26weblabAllocation\x3d"+c+n(d,g)},buildTriggerWeblabPathWithoutWeblab:function(a,b,c){return"/checkout/triggerWeblab?"+e(a)+n(b,c)}}});"use strict";k.when("turbo-checkout-page-ready").register("turbo-callback-list",function(){function d(){var c=[];this.callAll=function(){for(var a=0;a<c.length;a++){var b=c[a];b.apply(b,arguments)}};this.push=function(a){if("function"!==typeof a)throw"Invalid callback. Expected typeof 'callback' to be 'function'. typeof \x3d "+typeof a;-1===c.indexOf(a)&&
c.push(a)};this.remove=function(a){a=c.indexOf(a);-1!==a&&c.splice(a,1)}}return{create:function(){return new d}}});"use strict";k.when("turbo-callback-list","turbo-checkout-page-ready").register("turbo-filtered-callback-list",function(d){function c(a){var b=d.create();this.callAll=b.callAll;this.remove=b.remove;this.push=function(c){(c=c[a])&&"function"===typeof c&&b.push(c)}}return{create:function(a){if(!a||"string"!==typeof a)throw"Invalid filter parameter. Expected 'filter' to be a non empty string. typeof \x3d "+
typeof a+" value \x3d "+a;return new c(a)}}});"use strict";k.when("A","turbo-configuration","turbo-checkout-utils","turbo-checkout-page-ready").register("turbo-checkout-form",function(d,c,a){function b(a){var b=c.get(c.KEYS.FORM_SELECTOR_OVERRIDE);if(b&&0<e(b).length)return e(b);b=c.get(c.KEYS.FORM_TYPE);if("link"===b)return a.find("a");if("form"===b)return a.closest("form");throw"Unsupported FORM_TYPE is configured. value \x3d "+b;}var e=d.$,f=/[\/?&]ref_?=([^?&]+)/;return{getForms:b,getRefTag:function(c){if(1!==
c.length)return a.logError("Expected getRefTag input to have a single element. Cannot resolve refTag as this is a data quality risk","turbo-checkout-form"),a.logDebug("turbo-checkout-form","Expected getRefTag input to have a single element. Cannot resolve refTag as this is a data quality risk",c),"";c=b(c);c=((c.attr("action")||c.attr("href")||"")+"\x26"+c.serialize()).match(f)||{};return 2===c.length?c[1]:""}}});"use strict";k.when("A","turbo-checkout-csm","turbo-checkout-page-ready").register("turbo-checkout-ajax-wrapper",
function(d,c){return{load:function(a,b){b.hasOwnProperty("timeout")||(b.timeout=2E4);return d.ajax(a,b)},loadWithJQXHR:function(a,b){b.hasOwnProperty("timeout")||(b.timeout=2E4);return d.$.ajax(a,b)},createXHRRequest:function(){var a=new XMLHttpRequest;a.timeout=2E4;return a}}});"use strict";k.when("A","turbo-checkout-csm","turbo-checkout-utils","turbo-checkout-session-storage","turbo-checkout-quantity-input","turbo-checkout-address-id","turbo-checkout-warranty-input","turbo-checkout-accessories-input",
"turbo-checkout-page-ready").register("turbo-checkout-auto-open",function(d,c,a,b,e,f,h,n){function g(b,c){a.logDebug("turbo-checkout-auto-open",b,c)}function l(){return t()&&0!==k}function t(){var d;if(d="1"===r.trb_open||"1"===a.getUrlQueryParam("trb_open"))(d=b.isPresent("hasTurboAutoOpened"))&&c.logCount("turboCheckoutAutoOpenLoopPrevented"),d=!d;return d}function p(){return 1===k&&t()}function q(){p()&&(l()&&(k=2,b.set("hasTurboAutoOpened","1")),A(r.trb_bid),d.trigger("turbo:checkout:auto:open"))}
var z=d.$,k=0,u="trb_open trb_addr trb_qty trb_warrAsin trb_auth trb_sid trb_bid trb_accessoryAsin trb_accessoryOffer".split(" "),r={},A=function(){};return{setup:function(b,c){if(t()){k=1;var e=m.location.href;z.each(u,function(b,c){b=a.getUrlQueryParam(c);r[c]=b;e=a.removeQueryParam(c,b,e)});g("Parameters:",r);a.replaceHistory(e);"function"===typeof b?A=b:a.logError("Initiate action must be supplied, and it must be a function.");d.on("turbo:checkout:prefetcher:state:dataStale",q);c()}else k=0,g("Disabled")},
reset:function(){b.remove("hasTurboAutoOpened")},isAutoOpenEligible:t,isAutoOpenEnabled:l,isAutoOpenReadyToBeOpened:p,updateInputsAndThen:function(a){var b=r.trb_qty,c=r.trb_addr,d=r.trb_warrAsin,g=r.trb_bid,p=r.trb_accessoryAsin,t=r.trb_accessoryOffer;if(b||c||d||g||p||t){b&&e.setQuantity(b);c&&f.set(c);var q;d&&(h.select(d),q=h.getLineItem(b));var l;p&&t&&(n.select(p),l=n.getLineItem());a(b,c,q,g,l)}}}});"use strict";k.when("turbo-checkout-page-ready").register("turbo-checkout-utils",function(){function d(){return navigator.userAgent}
function c(a,b){if(a===b||"function"===typeof a&&"function"===typeof b)return!0;if(typeof a!==typeof b)return!1;if("object"!==typeof a||null===a||null===b)return a===b||a!==a&&b!==b;var d=Object.getOwnPropertyNames(a);if(d.length!==Object.getOwnPropertyNames(b).length)return!1;for(var f=0;f<d.length;f++){var h=d[f];if(!a.hasOwnProperty(h)||!b.hasOwnProperty(h)||!c(a[h],b[h]))return!1}return!0}return{logError:function(a,b){k.log(a,"ERROR",b||"turbo-checkout-utils")},logWarning:function(a,b){k.log(a,
"WARN",b||"turbo-checkout-utils")},logDebug:function(){},getUserAgent:d,isAndroid:function(){return!!d().match(/[a|A]ndroid/)},isIPhone:function(){return!!d().match(/iPhone/)},isIPad:function(){return!!d().match(/iPad/)},isInternetExplorer:function(){return!!d().match(/MSIE/)},createFQDN:function(a){/^http/.test(a)||(a=m.location.origin?m.location.origin+a:m.location.protocol+"//"+m.location.hostname+":"+m.location.port+a);return a},getUrlQueryParam:function(a,b){b||(b=m.location.href);a=a.replace(/[\[\]]/g,
"\\$\x26");return(a=(new RegExp("[?\x26]"+a+"(\x3d([^\x26#]*)|\x26|#|$)")).exec(b))?a[2]?decodeURIComponent(a[2].replace(/\+/g," ")):"":y},removeQueryParam:function(a,b,c){var d=c;a&&b&&c&&(a=a+"\x3d"+b,d=c.replace(new RegExp("\\?"+a+"[\x26]?","g"),"?"),d=d.replace(new RegExp("[\x26]?"+a,"g"),""));return d},replaceHistory:function(a){m.history.pushState&&m.history.replaceState(null,m.title,a)},isNonEmptyString:function(a){return"string"===typeof a&&0<a.length},isDeepEquals:c}});"use strict";k.when("turbo-checkout-utils",
"turbo-checkout-page-ready").register("turbo-checkout-csm",function(d){function c(a,c,d,e){return"function"===typeof m.uet?m.uet.apply(m.uet,arguments):e||b()}function a(a,b,c){return"function"===typeof m.ues?m.ues.apply(m.ues,arguments):c}function b(){return+new Date}function e(d){function e(){k&&f&&n&&h&&!m&&"function"===typeof u&&(u(k,f,n,h),m=!0)}var f,h,n,k,m=!1,u;this.getId=function(){return d};this.markClick=function(){k=c("tc",d)};this.markFirstByte=function(){f=a("t0",d,b())};this.markAboveTheFold=
function(){n=c("af",d);e()};this.markCriticalFeature=function(){h=c("cf",d);e()};this.whenDataSet=function(a){u=a;e()}}function f(a){"undefined"!==typeof m.ue_t0&&m.ue.count(a,Date.now()-m.ue_t0)}var h=0,n=[];return{createScope:function(){return new e("chk_turbo_"+ ++h)},logCount:function(a,b){b=b||1;d.logDebug("Logging counter "+a+" with value "+b);if(m.ue&&m.ue.count){var c=a+"_time";m.ue.count(a,b);f(c);for(var e=0;e<n.length;++e)m.ue.count(a+"."+n[e],b),f(c+"."+n[e])}},addCounterExtraSuffix:function(a){n.push(a)},
timestamp:b}});"use strict";k.when("A","turbo-checkout-csm","turbo-checkout-page-ready").register("turbo-checkout-counter",function(d,c){var a=0,b=0,e=0,f=0,h=0,n=0,g="u";d.on("turbo:checkout:sheet:beforeOpen",function(){c.logCount("turboCheckoutSheetOpen",a);"u"!==g?(++h,c.logCount("turboCheckoutPrefetchUsed",h),"p"===g?c.logCount("turboCheckoutPrefetchUsedInProgress",h):c.logCount("turboCheckoutPrefetchUsedFull",h)):(++n,c.logCount("turboCheckoutPrefetchMissing",n))});d.on("turbo:checkout:sheet:beforeClose",
function(){++b;c.logCount("turboCheckoutSheetClose",b)});d.on("turbo:checkout:prefetcher:state:dataPrefetching",function(){c.logCount("turboCheckoutPrefetchRequested",e);g="p"});d.on("turbo:checkout:prefetcher:state:dataFresh",function(){++f;c.logCount("turboCheckoutPrefetchAvailable",f);g="a"});d.on("turbo:checkout:prefetcher:state:dataStale",function(){g="u"});return{incrementSheetOpenedCounter:function(){a++},incrementPrefetchCounter:function(){e++},getSheetOpenCount:function(){return a},getPrefetchCount:function(){return e}}});
"use strict";k.when("turbo-checkout-page-ready").register("turbo-checkout-cacher",function(){return{createCache:function(d){var c=!1,a;return function(){c||(a=d(),c=!0);return a}}}});"use strict";k.when("A","turbo-configuration","turbo-checkout-utils","turbo-checkout-counter","turbo-checkout-page-ready").register("turbo-checkout-ref-tagger",function(d,c,a,b){function e(a,c,d){a="chk_"+a+"_"+(c+"_"+b.getPrefetchCount()+"-"+b.getSheetOpenCount());return f(d?a+"_"+d:a)}function f(a){if(!("string"===
typeof a&&0<a.length&&64>=a.length&&n.test(a))||g.test(a))throw"Invalid ref tag. This would be filtered and replaced in clickstream. Value \x3d "+a;return a}var h={ELIGIBILITY:"eligibility",BUY_NOW:"buyNow",CLOSE:"close"},n=/(^[A-z]$|^[A-z][A-z0-9_-]*[A-Za-z0-9]$)/,g=/[_-]{2,}/,l=c.get(c.KEYS.HOST_PAGE_TYPE_IDENTIFIER);return{generateRefTag:function(a,b,c){return"ref_\x3d"+e(a,b,c)},generateValue:e,generateJoinedValue:function(c){if(!c)return e(l,h.BUY_NOW,"fallback");try{var d=c+"_"+(h.BUY_NOW+"_"+
b.getPrefetchCount()+"-"+b.getSheetOpenCount());return f(d)}catch(g){return a.logError(g,"turbo-checkout-ref-tagger"),e(l,h.BUY_NOW,"fallback")}},generateEligibilityValue:function(){return e(l,h.ELIGIBILITY)},ACTIONS:h,TAGS:{TOUCH:"touch",TOUCH_X:"touchX",BACK:"back",ROTATION:"rotation"}}});"use strict";k.when("A","turbo-checkout-page-ready").register("turbo-checkout-prefetch-timer",function(d){function c(){f||(f=!0,d.trigger("turbo:checkout:timer:onTimeout"))}function a(){if(f)return!0;var a=(new Date).getTime();
return e?6E5<=a-e:!1}var b,e,f=!1;return{startTimer:function(){b||(b=m.setTimeout(c,6E5));e||(e=(new Date).getTime())},isTimeout:a,resetTimer:function(){m.clearTimeout(b);f=!1;e=b=null},checkTimeout:function(){a()&&c()}}});"use strict";k.when("A","jQuery","turbo-checkout-csm","turbo-checkout-utils","turbo-checkout-state-handler","turbo-checkout-form","turbo-checkout-buy-now-onclick-handler","turbo-configuration","turbo-checkout-page-ready").register("turbo-checkout-buy-now-button",function(d,c,a,
b,e,f,h,n){function g(a,c){b.logDebug("turbo-checkout-buy-now-button",a,c)}function l(a){return a?t(a):c(e.getInitiateSelector())}function t(d){var e=c("#"+d),f=n.get(n.KEYS.BUY_NOW_CSS_CLASS_TO_RESOLVE_DUPLICATE_BUTTON_ID);if(!f)return e;var h=c("[id\x3d"+d+"]");if(2>h.length)return e;a.logCount("turboCheckoutBuyNowDuplicateIdPresent");g("Duplicate nodes present for BuyNow button ID: #"+d+". Resolving BuyNow button with CSS: "+f);h=h.filter(f);return 1!==h.length?(a.logCount("turboCheckoutBuyNowUnableToResolveButtonIdWithCss"),
b.logError("Unable to resolve a unique BuyNow button with CSS: "+f+". Defaulting to first button with ID: #"+d,"turbo-checkout-buy-now-button",void 0),e):h}function p(b){g("Buy now button clicked");a.logCount("turboCheckoutBuyNowClicked");h.isConflictingOnClickListenerPresent(c(b.currentTarget))&&(D=!0);b&&b.currentTarget&&b.currentTarget.id||(g("Click event target is INVALID. Expected event target with an id. Turbo will NOT show",b),D=!0);if(D)D=!1,g("Buy now button callbacks supressed");else{e.resolveProductState(b.currentTarget.id);
var d;g("Calling buy now button callbacks...");d=!1;for(var n=0;n<v.length;n++)d=d||v[n]();d?(g("Supressing default buy now button action"),b.preventDefault(),b.stopPropagation(),b.stopImmediatePropagation(),d=!0):d=void 0;if(d)return!1}f.getForms(c(b.currentTarget)).attr("data-action",q());g("Calling default BuyNow action. User will be sent to Checkout SPC. Turbo will NOT show.");a.logCount("turboCheckoutBuyNowDefault");h.callCachedOnClickListenerIfPresent(b.currentTarget,b);return!0}function q(){return l().attr("name")||
"submit.buy-now"}function k(a){for(var b=v.length-1;0<=b;--b)v[b]===a&&v.splice(b,1)}function m(a){if(!a&&1<l().length)throw"Button id parameter is NOT present. Cannot execute action without a button id on a page with multiple buy now buttons!";}function u(a){a=l(a);r(a);a.click()}function r(b){for(var d=n.get(n.KEYS.CONFLICTING_INITIATE_LISTENERS),e=0;e<d.length;e++){var f=d[e];g("Unbound configured event '"+f+"' from buy now button");a.logCount("turboCheckoutBuyNowButtonConflictingListeners");b.unbind(f);
c(document.body).undelegate(b.selector,f)}}var A=n.get(n.KEYS.BUY_NOW_CLICK_EVENT),v=[],D=!1;d.on("turbo:checkout:clickInitiate",u);a.logCount("turboCheckoutBuyNowButtonBound");return{registerOnClickCallback:function(a){k(a);v.push(a)},deregisterOnClickCallback:k,executeOriginalBuyNowAction:function(a){m(a);D=!0;d.trigger("turbo:checkout:buyNowDisabled");d.trigger("turbo:checkout:clickInitiate",a)},executeTurboBuyNowAction:function(a){m(a);D=!1;u(a)},getSubmitAction:q,bindTurboClickEvent:function(a){a=
a||l();h.removeConflictingOnClickListenerIfPresentAndCacheIt(a);a.unbind(A).bind(A,p)},removeConflictingListeners:r,getBuyNowButtons:l}});"use strict";k.when("A","jQuery","turbo-checkout-csm","turbo-checkout-utils","turbo-checkout-page-ready").register("turbo-checkout-buy-now-onclick-handler",function(d,c,a,b){function e(a,b){a.each(function(a,d){c(d).removeProp(b)})}function f(a,b){var d=!1;a.each(function(){var a=c(this),e=a.find("[onclick]"),f=a.prop("onclick"),h=e.prop("onclick");return g(f)&&
g(h)||1<e.length||!g(f||h)||n(a)!==b?(d=!0,!1):!0});return d}function h(a){return a.prop("onclick")||a.find("[onclick]").prop("onclick")}function n(a){return a.attr("onclick")||a.find("[onclick]").attr("onclick")}function g(a){return"function"===typeof a}function l(a,c){b.logDebug("turbo-checkout-buy-now-onclick-handler",a,c)}var t;return{callCachedOnClickListenerIfPresent:function(b,c){g(t)&&(l("BuyNow button onclick listener function called."),a.logCount("turboCheckoutBuyNowButtonOnClickListenerCalled"),
t.call(b,c.originalEvent))},removeConflictingOnClickListenerIfPresentAndCacheIt:function(b){var c=h(b),d=n(b);g(c)&&d&&(f(b,d)?(l("[DOM ERROR] Turbo will NOT show. BuyNow button node has INVALID 'onclick' DOM structure.",b),a.logCount("turboCheckoutBuyNowButtonInvalidOnClickDOM")):(l("BuyNow button node has 'onclick' attribute. Removing its listener and caching it.",b),a.logCount("turboCheckoutBuyNowButtonOnClickListenerRemoveAndCache"),t=c,c=b.find("[onclick]"),e(b,"onclick"),e(c,"onclick")))},isConflictingOnClickListenerPresent:function(b){if(b=
g(h(b)))l("Turbo will NOT show. BuyNow button node has conflicting 'onclick' listener."),a.logCount("turboCheckoutBuyNowButtonConflictingOnClickListener");return b}}});"use strict";k.when("A","turbo-checkout-utils","turbo-checkout-buy-now-button","turbo-checkout-page-ready").register("turbo-checkout-buy-now-integration",function(d,c,a){function b(a,b){c.logDebug(a,"turbo-checkout-buy-now-integration",b)}var e=d.$,f=[];d.on("turbo:checkout:page:reappear",function(){b("Removing additional form inputs from form",
f);for(var a;(a=f.shift())!==y;)a.remove()});return{isBuyNow:function(b){return b instanceof e&&b.attr("data-action")===a.getSubmitAction()},checkoutWith:function(a,d){if(Array.isArray(a)&&d instanceof e){var g;g=d;for(var l=1;0<g.find('input[name\x3d"asin.'+l+'"]').length||0<g.find('input[name\x3d"offeringID.'+l+'"]').length;)l++;g=l;for(var l=[],t=0;t<a.length;t++){var p=a[t];if(p!==y&&p.asin&&p.offerListingId){var k=g,p=[e("\x3cinput /\x3e",{type:"hidden",name:"asin."+k,value:p.asin}),e("\x3cinput /\x3e",
{type:"hidden",name:"offeringID."+k,value:p.offerListingId}),e("\x3cinput /\x3e",{type:"hidden",name:"quantity."+k,value:p.quantity||1})];Array.prototype.push.apply(l,p);g++}else b('Line item inputs are invalid. Expected "asin" and "offerListingId" keys in object. Customer purchase inputs ignored!',p),c.logError('Line item inputs are invalid. Expected "asin" and "offerListingId" keys in object. Customer purchase inputs ignored!')}t=d.find('input[name\x3d"itemCount"]');1===t.length?t.val(g):d.append(e("\x3cinput /\x3e",
{type:"hidden",name:"itemCount",value:g}));b("Appended additional buy now inputs.",l);d.append.apply(d,l);f=l}else g="Inputs are invalid. Expected array and jQuery object. lineItems \x3d "+a+" $form \x3d "+d,b(g,arguments),c.logError(g)}}});"use strict";k.when("turbo-checkout-page-ready").register("turbo-configuration-keys",function(d){var c={HOST_PAGE_TYPE_IDENTIFIER:"HOST_PAGE_TYPE_IDENTIFIER",FORM_TYPE:"FORM_TYPE",FORM_SELECTOR_OVERRIDE:"FORM_SELECTOR_OVERRIDE",BUY_NOW_BUTTON_SELECTOR:"BUY_NOW_BUTTON_SELECTOR",
BUY_NOW_BUTTON_V2_SELECTOR:"BUY_NOW_BUTTON_V2_SELECTOR",BUY_NOW_CLICK_EVENT:"BUY_NOW_CLICK_EVENT",BUY_NOW_CSS_CLASS_TO_RESOLVE_DUPLICATE_BUTTON_ID:"BUY_NOW_CSS_CLASS_TO_RESOLVE_DUPLICATE_BUTTON_ID",QUANTITY_SELECT_SELECTOR:"QUANTITY_SELECT_SELECTOR",ADDRESS_INPUT_SELECTORS:"ADDRESS_INPUT_SELECTORS",WARRANTY_CHECKBOX_INPUT_SELECTOR:"WARRANTY_CHECKBOX_INPUT_SELECTOR",WARRANTY_CHECKBOX_RELATIVE_PARENT_SELECTOR:"WARRANTY_CHECKBOX_RELATIVE_PARENT_SELECTOR",WARRANTY_ASIN_INPUT_NAME:"WARRANTY_ASIN_INPUT_NAME",
WARRANTY_OFFER_INPUT_SELECTOR:"WARRANTY_OFFER_INPUT_SELECTOR",AJAX_PAGE_UPDATE_EVENT:"AJAX_PAGE_UPDATE_EVENT",PREFETCH_TREATMENT:"PREFETCH_TREATMENT",NO_PREFETCH_TREATMENT:"NO_PREFETCH_TREATMENT",BUY_NOW_ONLY_TREATMENT:"BUY_NOW_ONLY_TREATMENT",IS_DEVICE_FILTER_REQUIRED:"IS_DEVICE_FILTER_REQUIRED",IS_SIGN_IN_SUPPORTED:"IS_SIGN_IN_SUPPORTED",USES_MASH_WILL_REAPPEAR:"USES_MASH_WILL_REAPPEAR",SHOW_SIGN_IN_INTERFACE:"SHOW_SIGN_IN_INTERFACE",IFRAME_ID:"IFRAME_ID",EXTEND_ELIGIBLE_STATE:"EXTEND_ELIGIBLE_STATE",
VIEW_ADAPTER:"VIEW_ADAPTER",PAGE_STATE_PARSING_ROOT_NODE_SELECTOR:"PAGE_STATE_PARSING_ROOT_NODE_SELECTOR",PRODUCT_STATE_PARSING_ROOT_NODE_SELECTOR:"PRODUCT_STATE_PARSING_ROOT_NODE_SELECTOR",TURBO_PAGE_STATE_KEY:"TURBO_PAGE_STATE_KEY",TURBO_PRODUCT_STATE_KEY:"TURBO_PRODUCT_STATE_KEY",DEVICE_OVERRIDE:"DEVICE_OVERRIDE",CONFLICTING_INITIATE_LISTENERS:"CONFLICTING_INITIATE_LISTENERS",VAS_CHANGE_EVENTS:"VAS_CHANGE_EVENTS",VAS_CHECKBOX_SELCTOR:"VAS_CHECKBOX_SELCTOR",CHECKBOX_EXCLUSION_ROOT_NODES:"CHECKBOX_EXCLUSION_ROOT_NODES",
MASH_ADAPTER:"MASH_ADAPTER",IS_ADD_TO_CART_ENABLED:"IS_ADD_TO_CART_ENABLED",IS_BUYNOW_ENABLED_FOR_SCREENREADER:"IS_BUYNOW_ENABLED_FOR_SCREENREADER",BACKGROUND_SCROLL_TARGET_SELECTOR:"BACKGROUND_SCROLL_TARGET_SELECTOR",NO_PREFETCH_EXPERIMENT_WEBLABS:"NO_PREFETCH_EXPERIMENT_WEBLABS",ENABLED_ACCESSORIES_SELECTOR:"ENABLED_ACCESSORIES_SELECTOR",OVERRIDE_ELIGIBILITY:"OVERRIDE_ELIGIBILITY",validate:function(a){if("string"!==typeof a||!c[a])throw"The key '"+a+"' is not defined within 'turbo-configuration-keys'.";
}};return c});"use strict";k.when("A","turbo-configuration-keys","turbo-device-configuration","turbo-client-configuration","turbo-eligibility-override","turbo-checkout-page-ready").register("turbo-configuration",function(d,c,a,b,e){function f(a,b){var c=h(a);l[a]=c===y?b:c}function h(c){var d=b[c];c=a[c];if(n(d))return d;if(n(c))return c}function n(a){return"boolean"===typeof a||a}function g(c){if(!n(b[c])&&!n(a[c]))throw"Required configuration override for key '"+c+"' is missing";l[c]=h(c)}var l;
return{get:function(a){c.validate(a);var b;l||(l={},g(c.HOST_PAGE_TYPE_IDENTIFIER),g(c.SHOW_SIGN_IN_INTERFACE),g(c.EXTEND_ELIGIBLE_STATE),g(c.VIEW_ADAPTER),f(c.FORM_TYPE,"form"),f(c.FORM_SELECTOR_OVERRIDE,""),f(c.BUY_NOW_BUTTON_SELECTOR,"#buy-now-button"),f(c.BUY_NOW_BUTTON_V2_SELECTOR,".checkout-buy-now"),f(c.BUY_NOW_CLICK_EVENT,"click.turboCheckout"),f(c.BUY_NOW_CSS_CLASS_TO_RESOLVE_DUPLICATE_BUTTON_ID,""),f(c.QUANTITY_SELECT_SELECTOR,'select[name\x3d"quantity"]'),f(c.ADDRESS_INPUT_SELECTORS,["#unifiedLocation1ClickAddress",
"#unifiedLocationAddress"]),f(c.WARRANTY_CHECKBOX_INPUT_SELECTOR,".mbb-checkbox input[name\x3dmbba]"),f(c.WARRANTY_CHECKBOX_RELATIVE_PARENT_SELECTOR,".mbb-checkbox-column"),f(c.WARRANTY_ASIN_INPUT_NAME,"mbba"),f(c.WARRANTY_OFFER_INPUT_SELECTOR,"#mbb-offering-id"),f(c.AJAX_PAGE_UPDATE_EVENT,"a:pageUpdate"),f(c.PREFETCH_TREATMENT,"PREFETCH_DISABLED"),f(c.NO_PREFETCH_TREATMENT,"T1"),f(c.BUY_NOW_ONLY_TREATMENT,"BUY_NOW_LAUNCHED"),f(c.IS_DEVICE_FILTER_REQUIRED,!1),f(c.IS_SIGN_IN_SUPPORTED,!0),f(c.USES_MASH_WILL_REAPPEAR,
!1),f(c.IFRAME_ID,"turbo-checkout-iframe"),f(c.PAGE_STATE_PARSING_ROOT_NODE_SELECTOR,"#turboState"),f(c.PRODUCT_STATE_PARSING_ROOT_NODE_SELECTOR,"#turboState"),f(c.TURBO_PAGE_STATE_KEY,"turbo-checkout-page-state"),f(c.TURBO_PRODUCT_STATE_KEY,"turbo-checkout-page-state"),f(c.DEVICE_OVERRIDE,""),f(c.CONFLICTING_INITIATE_LISTENERS,[]),f(c.CHECKBOX_EXCLUSION_ROOT_NODES,"#simpleBundle_feature_div #monthlyPayments_feature_div #bbg_feature_div #addons_feature_div #mobile-accessory-upsell #detailPageGifting_feature_div #twister-plus-feature".split(" ")),
f(c.ENABLED_ACCESSORIES_SELECTOR,".simpleBundleCheckBoxArea"),f(c.MASH_ADAPTER,""),f(c.IS_ADD_TO_CART_ENABLED,!0),f(c.IS_BUYNOW_ENABLED_FOR_SCREENREADER,!0),f(c.BACKGROUND_SCROLL_TARGET_SELECTOR,"#productTitleGroupAnchor"),f(c.VAS_CHANGE_EVENTS,["turbo:checkout:sheet:doClose"]),f(c.VAS_CHECKBOX_SELCTOR,"#vas-checkbox-input"),f(c.VAS_CHANGE_EVENTS,["turbo:checkout:sheet:doClose"]),f(c.VAS_CHECKBOX_SELCTOR,"#vas-checkbox-input"),f(c.NO_PREFETCH_EXPERIMENT_WEBLABS,["RCX_CHECKOUT_TURBO_PRIME_UPSELL_222066"]),
f(c.OVERRIDE_ELIGIBILITY,e));b=l;return b[a]},KEYS:d.copy(c)}});"use strict";k.when("turbo-checkout-utils","turbo-checkout-weblab-allocation","turbo-checkout-state-handler","turbo-checkbox-exclusion-listener","turbo-checkout-content-loader","turbo-checkout-device-filter","turbo-callback-list","turbo-checkout-auto-open","turbo-checkout-vas-input","turbo-checkout-accessories-input","turbo-checkout-page-ready").register("turbo-base-eligible-state",function(d,c,a,b,e,f,h,n,g,l){function k(){A=!0}function p(){A=
!1}function q(){var d=new m;f.isDeviceTurboEligible()||d.invalidate("Device is NOT eligible");e.isError()&&!c.isNoPrefetch()&&d.invalidate("Prefetch failed");a.isProductTurboEligible()||d.invalidate("Product is NOT eligible");n.isAutoOpenEnabled()||A||d.invalidate("Cheetah eligibility response is false");c.isControl()&&d.invalidate("Weblab is in CONTROL");c.isBuyNowOnly()&&d.invalidate("Weblab is in buy now only treatment");g.isSelected()&&d.invalidate("Value added service is selected and NOT supported");
l.isEligible()||d.invalidate("Accessory selection was not eligible");b.isAnyCheckboxChecked()&&d.invalidate("Exclusion case checkbox is checked");u.callAll(d);d.logInvalidState();return d.canShow()}function m(){var a=!0,b=[];this.invalidate=function(c){a=!1;b.push(c)};this.logInvalidState=function(){a||d.logDebug("turbo-base-eligible-state","Cannot show turbo because: "+b)};this.canShow=function(){return a}}function w(a){r.callAll(q(),a)}var u=h.create(),r=h.create(),A=!1;return{addStateCheck:function(a){u.push(a)},
canShow:q,registerStateChangeCallback:function(a){r.push(a)},onStateChange:w,setup:function(){e.registerCallback({onTurboEligible:k,onFinish:k,onTurboIneligible:p});a.registerCallback(w);b.onStateChange(w);g.onChange(w);l.registerCallback(w)}}});"use strict";k.when("A","turbo-callback-list","turbo-checkout-page-ready").register("turbo-checkout-base-view",function(d,c){function a(a){if("string"!==typeof a)throw"Parameter 'iFrameContainerSelector' is not a string.";this.onBoundsAdjustedCallbacks=c.create();
this.IFRAME_CONTAINER_SELECTOR=a}var b=d.$;a.prototype.updateBounds=function(a,b){if("number"!==typeof a)throw'Parameter "iFrameContainerHeightInPixels" is not a number. Cannot validate bounds.';var c=this.$getIFrameContainer().height(),d=a-c,g=c+d;0!==d&&(this.$getIFrameContainer().height(g),b&&a!==b?(this.$getIFrame().height(b),this.$getIFrameContainer().css("overflow-y","scroll"),this.$getIFrameContainer().css("-webkit-overflow-scrolling","touch")):(this.$getIFrame().height("100%"),this.$getIFrameContainer().css("overflow-y",
""),this.$getIFrameContainer().css("-webkit-overflow-scrolling","")),a=parseInt(this.$getIFrameContainer().css("min-height"),10),g=g>a?g:a,c!==g&&this.onBoundsAdjustedCallbacks.callAll(g))};a.prototype.$getIFrameContainer=function(){return b(this.IFRAME_CONTAINER_SELECTOR)};a.prototype.$getIFrame=function(){return b(this.IFRAME_CONTAINER_SELECTOR+" iframe")};a.prototype.pushBoundsAdjustedCallback=function(a){this.onBoundsAdjustedCallbacks.push(a)};return{extend:function(){function b(){a.apply(this,
arguments)}b.prototype=Object.create(a.prototype);return b.prototype.constructor=b}}});"use strict";k.when("turbo-configuration","turbo-checkout-page-ready").execute("turbo-eligible-state-check",function(d){d.get(d.KEYS.EXTEND_ELIGIBLE_STATE)||k.when("turbo-base-eligible-state").register("turbo-checkout-eligible-state",function(c){return{canShow:c.canShow,registerStateChangeCallback:c.registerStateChangeCallback,setup:c.setup}})});"use strict";k.when("A","turbo-checkout-state-handler","turbo-configuration",
"turbo-checkout-utils","turbo-checkout-page-ready").register("turbo-checkout-weblab-allocation",function(d,c,a){function b(){return c.getWeblabAllocation()}function e(){return c.getExperimentName()}function f(){return"C"===b()}function h(){var b=a.get(a.KEYS.NO_PREFETCH_EXPERIMENT_WEBLABS);return Array.isArray(b)&&-1!==b.indexOf(e())&&!f()}return{getAllocation:b,getExperimentName:e,isControl:f,isBuyNowOnly:function(){return b()===a.get(a.KEYS.BUY_NOW_ONLY_TREATMENT)},isPrefetch:function(){return!h()&&
b()===a.get(a.KEYS.PREFETCH_TREATMENT)},isNoPrefetch:function(){var c=a.get(a.KEYS.NO_PREFETCH_TREATMENT);return h()||!!b().match(c)}}});"use strict";k.when("A","jQuery","turbo-checkout-ajax-wrapper","turbo-checkout-utils","turbo-checkout-urls","turbo-checkout-csm","turbo-checkout-weblab-allocation","turbo-checkout-buy-now-button","turbo-checkout-form","turbo-configuration","turbo-checkout-state-handler","turbo-checkout-eligibility-response-weblabs","turbo-checkout-page-ready").register("turbo-checkout-weblab-trigger",
function(d,c,a,b,e,f,h,n,g,l,k,p){function q(){d.on("turbo:checkout:prefetch:onTurboEligible",function(){E=!0;r()})}function z(){d.on("turbo:checkout:prefetch:onTurboIneligible",function(){E=!1;r()})}function w(){d.on("a:pageUpdate",function(){r()})}function u(){d.on("turbo:checkout:auto:open",function(){D()})}function r(){0===A().length?f.logCount("turboCheckoutBuyNowButtonMissing"):0===g.getForms(A()).length&&f.logCount("turboCheckoutBuyNowFormMissing");0<g.getForms(A()).length&&(E?(b.logDebug("turbo-checkout-weblab-trigger",
"Adding trigger to form: "+h.getAllocation()),B.val(h.getAllocation()),y.val(h.getExperimentName()),G.val(k.getRequestId()),C.val(k.getSessionId()),g.getForms(A()).append(B,y,G,C)):(b.logDebug("turbo-checkout-weblab-trigger","Removing trigger from form: "+h.getAllocation()),B.remove(),y.remove(),G.remove(),C.remove()))}function A(){var a=l.get(l.KEYS.BUY_NOW_BUTTON_SELECTOR),b=l.get(l.KEYS.BUY_NOW_BUTTON_V2_SELECTOR);return 0===c(a).length?c(b):c(a)}function v(){if(p.get()&&0<p.get().length||E&&!k.isTurboLaunched())b.logDebug("turbo-checkout-weblab-trigger",
"Calling cheetah to trigger: "+h.getAllocation()),0<g.getForms(A()).find(B).length||f.logCount("turboCheckoutTriggerMissing"),D(!E||k.isTurboLaunched())}function D(a){a=a?e.buildTriggerWeblabPathWithoutWeblab(k.getRefTag,k.getRequestId(),k.getSessionId()):e.buildTriggerWeblabPathWith(k.getRefTag(),h.getExperimentName(),h.getAllocation(),k.getRequestId(),k.getSessionId());var b={additionalWeblabsToTrigger:JSON.stringify(p.get())},d="function"===typeof m.Blob;"function"===typeof m.navigator.sendBeacon&&
d?(b=new Blob([c.param(b)],{type:"application/x-www-form-urlencoded"}),m.navigator.sendBeacon(a,b)||f.logCount("turboCheckoutTriggerRecordingFailed")):x(a,b)}function x(b,c){a.load(b,{method:"POST",params:c,error:function(a,b,c){a&&204===a.http.status||f.logCount("turboCheckoutTriggerRecordingFailed")},abort:function(a){f.logCount("turboCheckoutTriggerRecordingFailed")}})}var B,y,G,C,E=!1;return{setup:function(){B=c("\x3cinput/\x3e",{type:"hidden",name:"triggerTurboWeblab",value:""});y=c("\x3cinput/\x3e",
{type:"hidden",name:"triggerTurboWeblabName",value:""});G=c("\x3cinput/\x3e",{type:"hidden",name:"turboPageRequestId",value:""});C=c("\x3cinput/\x3e",{type:"hidden",name:"turboPageSessionId",value:""});w();q();z();n.registerOnClickCallback(v);u()}}});"use strict";k.when("A","turbo-checkout-form","turbo-checkout-utils","turbo-checkout-state-handler","turbo-checkout-page-ready").register("turbo-checkout-page-filter",function(d,c,a,b){function e(b,c){a.logDebug("turbo-checkout-page-filter",b,c)}return{isCurrentViewTurboEligible:function(){var a=
d.$(b.getInitiateSelector()),h=c.getForms(a),n=0<a.length&&a.length===h.length;n||(e("Page is NOT turbo eligible. Parent forms / nested links do not match the number of initiate selectors",a),e("Forms",h));return n}}});"use strict";k.when("turbo-configuration","turbo-checkout-page-ready").execute("turbo-device-filter-check",function(d){d.get(d.KEYS.IS_DEVICE_FILTER_REQUIRED)||k.when("turbo-checkout-cacher","turbo-checkout-page-ready").register("turbo-checkout-device-filter",function(c){var a=function(){return!0};
return{isDeviceTurboEligible:c.createCache(a),isSignInSupported:c.createCache(a)}})});"use strict";k.when("A","turbo-checkout-state-handler","turbo-checkout-device-filter","turbo-checkout-page-filter","turbo-checkout-weblab-allocation","turbo-checkout-page-ready").register("turbo-checkout-eligibility-aggregator",function(d,c,a,b,e){return{isTurboEligible:function(){return b.isCurrentViewTurboEligible()&&c.isProductTurboEligible()&&!e.isBuyNowOnly()},isSignInSupported:function(){return a.isSignInSupported()&&
!e.isBuyNowOnly()},shouldAttemptPrefetch:function(){return a.isDeviceTurboEligible()&&!e.isBuyNowOnly()}}});"use strict";k.when("A","turbo-checkout-ref-tagger","turbo-filtered-callback-list","turbo-checkout-state-handler","turbo-checkout-ajax-wrapper","turbo-checkout-utils","turbo-checkout-urls","turbo-checkout-csm","turbo-checkout-eligibility-aggregator","turbo-checkout-eligibility-response-weblabs","turbo-checkout-accessories-input","turbo-checkout-page-ready").register("turbo-checkout-content-loader",
function(d,c,a,b,e,f,h,n,g,k,t){function p(a){n.logCount("turboCheckoutInitiate");K();M=!1;L=Date.now();u("Notifying loading callbacks");F="started";P.callAll();d.trigger("turbo:checkout:prefetch:onStart");n.logCount("turboCheckoutPrefetchStart");var f=a?c.generateEligibilityValue():b.getRefTag(),f=(a?h.buildEligibilityPathWith:h.buildInitiatePathWith)(f,b.getExperimentName(),b.getRequestId(),b.getSessionId());E=e.loadWithJQXHR(f,{type:"POST",data:q(a),headers:z(),xhr:w,success:v,error:D})}function q(a){var c=
{isAsync:1};b.getAddressId()&&(c.addressID=b.getAddressId());b.isPhysicalGiftCardExperimentEligible()&&(c.isPhysicalGiftCard=b.isPhysicalGiftCardExperimentEligible());if(a&&t.isEligible()&&t.getLineItem()){var d=t.getLineItem();c["asin.1"]=d.asin;c["offerListing.1"]=d.offerListingId;c["requiresEligibilityCheck.1"]="true"}a||b.getLineItems().forEach(function(a,b){b+=1;c["asin."+b]=a.asin;c["offerListing."+b]=a.offerListingId;c["quantity."+b]=a.quantity;a.customItemPrice&&(c["customItemPrice."+b]=a.customItemPrice,
c.customItemPrice=a.customItemPrice);var d=a.addToCartTimeAsUnixEpochMilliseconds;d&&(c["addToCartTimeAsUnixEpochMilliseconds."+b]=d);(a=a.addToCartSessionId)&&(c["addToCartSessionId."+b]=a)});return c}function z(){var a={"x-amz-support-custom-signin":1};a["x-amz-turbo-checkout-dp-url"]=m.location.href;a["x-amz-checkout-entry-referer-url"]=m.location.href;return a}function w(){var a=e.createXHRRequest();a.addEventListener("readystatechange",function(){if(M||!a.readyState||2>a.readyState)u("Ignoring ready state changed event because headers already received or missing xhr");
else if(M=!0,n.logCount("turboCheckoutPrefetchHeadersReceived"),n.logCount("turboCheckoutPrefetchHeadersReceivedDuration",Date.now()-L),x(a)){u("Headers received: Turbo eligible");n.logCount("turboCheckoutTurboEligibleAfterCheetahChecks");var b=r(a),c=g.isSignInSupported();b&&(u("Headers received: Signin required"),n.logCount("turboCheckoutSigninRequired"),c||(u("Sign-in required but it is disabled or not supported."),n.logCount("turboCheckoutSigninNotSupported")));if(c||!b)u("Notifying turbo eligible callbacks"),
I.callAll(),d.trigger("turbo:checkout:prefetch:onTurboEligible");A(a)&&R.callAll(a.getResponseHeader("x-amzn-checkout-login-provider"))}else u("Headers received: Not turbo eligible"),S.callAll(),d.trigger("turbo:checkout:prefetch:onTurboIneligible")});return a}function u(a,b){f.logDebug("turbo-checkout-content-loader",a,b)}function r(a){return a&&a.getResponseHeader("x-amzn-checkout-login-required")}function A(a){return g.isSignInSupported()&&r(a)}function v(a,b,c){n.logCount("turboCheckoutPrefetchEnd",
Date.now()-L);E=null;b=x(c);var e,g=a&&a.match(G);if(g&&0<g.length)try{var h=C(g[0]);e=C.parseJSON(h.text())}catch(q){f.logError("Could not extract page state from cheetah page: "+q)}else u("Could not extract page state from response data");var h=e&&"turbo"===e.pipelineType,g=e&&e.currentPurchaseId&&0<String(e.currentPurchaseId).trim().length,p=c.getResponseHeader("x-amzn-experiment-weblabs-to-trigger");if(p!==y){var m=[];try{m=JSON.parse(p)}catch(q){console.error("Error parsing additional weblabs from xhr response header: ",
q)}k.set(m)}h&&!g&&f.logError("No purchaseid provided, cannot show turbo");b&&h&&g?("started"!==F&&f.logError("turbo-checkout-content-loader","Error processing turbo available callbacks. Expected state to be started but was "+F),u("Notifying turbo available callbacks"),F="success",Q.callAll(a,e),d.trigger("turbo:checkout:prefetch:onSuccess"),n.logCount("turboCheckoutTurboPrefetchSuccess")):b&&A(c)?u("Body received: Eligible and sign-in is supported and required."):(u("Body received: No turbo page or not eligible: isTurboEligible: "+
b+" isTurboPage: "+h+" hasPurchaseId: "+g),B(),n.logCount("turboCheckoutTurboPrefetchFail"))}function D(a,b,c){n.logCount("turboCheckoutPrefetchEnd");E=null;u("Error while initiate",c);n.logCount("turboCheckoutTurboPrefetchError");"timeout"===b&&n.logCount("turboCheckoutInitiateTimeOut");B()}function x(a){return a&&a.getResponseHeader("x-amz-turbo-checkout-eligible")}function B(){"started"!==F&&f.logError("turbo-checkout-content-loader","Error processing turbo not available callbacks. Expected state to be started but was "+
F);u("Notifying error callbacks");F="error";O.callAll();d.trigger("turbo:checkout:prefetch:onError")}function K(){E&&E.abort&&(u("Aborting running request..."),E.abort())}var G=/<script.*data-a-state.*checkout:conductor:page.*>.*<\/script>/,C=d.$,E,F="stopped",L,M=!1,P=a.create("onStart"),Q=a.create("onFinish"),O=a.create("onError"),I=a.create("onTurboEligible"),S=a.create("onTurboIneligible"),R=a.create("onSigninRequired");d.on("turbo:checkout:signInController:onDoSignIn",B);return{registerCallback:function(a){P.push(a);
Q.push(a);O.push(a);I.push(a);R.push(a);S.push(a)},callInitiate:function(){u("Calling turbo initiate");p()},checkEligibility:function(){u("Calling turbo eligibility check only");p(!0)},abortCall:K,isSuccess:function(){return"success"===F},isError:function(){return"error"===F},isStarted:function(){return"started"===F}}});"use strict";k.when("A","jQuery","turbo-checkout-ref-tagger","turbo-checkout-utils","turbo-checkout-page-ready").register("turbo-checkout-history-manager",function(d,c,a,b){function e(){if(m.history.state&&
m.history.state.turboAction)return m.history.state.turboAction}c(m).bind("popstate.turbo",function(c){e();e()?(b.logDebug("turbo-checkout-history-manager","Trigger sheet open"),d.trigger("turbo:checkout:sheet:doOpen")):(b.logDebug("turbo-checkout-history-manager","Trigger sheet close"),d.trigger("turbo:checkout:sheet:doClose",{immediate:!1,reason:a.TAGS.BACK}))});return{sheetOpened:function(){e();e()||(b.logDebug("turbo-checkout-history-manager","Adding turbo history state"),m.history.pushState({turboAction:"popover"},
document.title+" Turbo open"))},sheetClosed:function(){e();e()&&(b.logDebug("turbo-checkout-history-manager","Removing turbo history state"),m.history.back())}}});"use strict";k.when("A","turbo-checkout-page-ready").register("turbo-base-visibility-manager",function(d){function c(){d.trigger("turbo:checkout:page:gone")}return{setup:function(){d.on("turbo:checkout:sheet:onNavigateAway",c)}}});k.when("turbo-configuration","turbo-checkout-page-ready").execute("turbo-mash-will-reappear-check",function(d){d.get(d.KEYS.USES_MASH_WILL_REAPPEAR)||
k.when("turbo-base-visibility-manager").register("turbo-checkout-page-visibility-manager",function(c){return c})});"use strict";k.when("A","jQuery","turbo-checkout-view-state","turbo-checkout-weblab-allocation","turbo-checkout-state-handler","turbo-checkout-content-loader","turbo-checkout-prefetch-timer","turbo-checkout-page-visibility-manager","turbo-checkout-counter","turbo-checkout-utils","turbo-checkout-eligibility-aggregator","turbo-checkout-auto-open","turbo-checkout-page-ready").register("turbo-checkout-prefetcher",
function(d,c,a,b,e,f,h,k,g,l,m,p){function q(a){var b=w;w=a;l.logDebug("turbo-checkout-prefetcher","Transitioning from "+b.name+" to "+a.name);if(b.onExit)b.onExit(a.name);if(a.onEnter)a.onEnter(b.name);d.trigger("turbo:checkout:prefetcher:state:"+a.name);d.trigger("turbo:checkout:prefetcher:state",a.name)}var z,w,u=function(){var a=f.isError(),b=!m.isTurboEligible(),c=h.isTimeout(),d=0===z;l.logDebug("turbo-checkout-prefetcher","Test is data stale: isStaleWhenCheetahReturnsError: "+a+" isStaleWhenProductNotEligiblie: "+
b+" isStaleWhenTimeoutOccurs: "+c+" isStaleWhenNoMorePrefetchesAvailable: "+d);return a||b||c||d},r=function(){var a=m.isTurboEligible()&&!h.isTimeout()&&0<z;l.logDebug("turbo-checkout-prefetcher","Test should prefetch: eligibilityAggregator.isTurboEligible(): "+m.isTurboEligible()+" !timer.isTimeout(): "+!h.isTimeout()+" _prefetchesAvailable: "+z);return a},A={name:"start",onEvent:function(a){m.shouldAttemptPrefetch()?"controller:onPageLoaded"===a&&q(v):q(B)},onExit:function(){e.startMonitoringPage()}},
v={name:"dataStale",onEvent:function(a){"page:gone"!==a&&"prefetch:onError"!==a&&"sheet:afterClose"!==a&&r()&&q(y)}},y={name:"dataPrefetching",onEnter:function(){g.incrementPrefetchCounter();b.isPrefetch()||a.isOpeningOrOpen()||p.isAutoOpenReadyToBeOpened()?f.callInitiate():f.checkEligibility();--z},onEvent:function(a){if("page:gone"===a)q(v);else{var c=f.isSuccess()&&b.isPrefetch(),d=f.isSuccess()&&b.isNoPrefetch();l.logDebug("turbo-checkout-prefetcher","Test is data fresh: isFreshWhenPrefetchResultOKInT1: "+
c+" isFreshWhenPrefetchResultOKInT4: "+d);c||d?q(x):u()?q(v):"product:onChange"===a&&r()&&q(y)}},onExit:function(a){"dataFresh"!==a&&f.abortCall()}},x={name:"dataFresh",onEnter:function(){h.startTimer()},onEvent:function(b){"page:gone"===b?q(v):u()?q(v):(a.isClosed()||"product:onChange"===b)&&r()&&q(y)},onExit:function(){h.resetTimer()}},B={name:"end"},K="controller:onPageLoaded sheet:beforeOpen sheet:afterClose product:onChange prefetch:onSuccess prefetch:onError timer:onTimeout page:gone page:reappear".split(" "),
G={"sheet:beforeOpen":function(){z=10}};return{setup:function(){z=10;w=A;c.each(K,function(a,b){var c=G[b];d.on("turbo:checkout:"+b,function(a){l.logDebug("turbo-checkout-prefetcher","Processing "+b);c&&c();if(w.onEvent)w.onEvent(b)})})},getState:function(){return w.name}}});"use strict";k.when("A","turbo-signin-adapter","turbo-checkout-content-loader","turbo-checkout-buy-now-button","turbo-checkout-csm","turbo-checkout-weblab-allocation","turbo-checkout-utils","turbo-callback-list","turbo-checkout-state-handler",
"turbo-checkout-eligible-state","turbo-checkout-page-ready").register("turbo-checkout-signin-controller",function(d,c,a,b,e,f,h,k,g,l){function m(){r=!1}function p(a){r=!0;A=a;e.logCount("turboCheckoutSigninRequired")}function q(){var a=r&&l.canShow();a&&(h.logDebug("turbo-checkout-signin-controller","Showing sign in dialog"),e.logCount("turboCheckoutSigninPopup"),c.show(A,z,w),d.trigger("turbo:checkout:signInController:onDoSignIn"));return a}function z(){h.logDebug("turbo-checkout-signin-controller",
"Signin success");e.logCount("turboCheckoutSigninSuccess");u.callAll()}function w(){h.logDebug("turbo-checkout-signin-controller","Signin failed");e.logCount("turboCheckoutSigninFailed")}var u=k.create(),r=!1,A;return{setup:function(){a.registerCallback({onStart:m,onSigninRequired:p});b.registerOnClickCallback(q)},registerCallback:u.push}});"use strict";k.when("A","turbo-configuration","turbo-callback-list","turbo-filtered-callback-list","turbo-checkout-page-ready").register("turbo-checkout-iframe",
function(d,c,a,b){function e(){return d.$("#"+l)}function f(){if(!(0<e().length))throw"Attempted to read / write the iFrame without it being in the DOM. This would result in an undefined iFrame document.";var a=e()[0];return a.contentDocument||a.contentWindow.document}function h(){if(0<e().length)throw"Attempted to insert multiple Turbo Checkout iFrames";}function k(){return d.$("\x3ciframe/\x3e",{id:l,src:"about:blank",scrolling:"no","class":"turbo-checkout-blank"})}function g(a){q.push(a)}var l=
c.get(c.KEYS.IFRAME_ID),m=b.create("beforeFramePopulated"),p=b.create("afterFramePopulated"),q=a.create();g(function(a){a.addClass("turbo-checkout-shown")});d.on("turbo:checkout:iframe:document:loaded",function(){q.callAll(e())});return{write:function(a){m.callAll();a+='\x3cscript\x3e"use strict";window.parent.P.now("turbo-checkout-controller").execute("callbackPageController", function callbackPageController(controller) {controller.frameHtmlRendered();});P.when("load").execute("onTurboDocumentLoaded", function onTurboDocumentLoaded() {window.parent.P.when("A").execute("triggerTurboDocumentLoaded", function triggerTurboDocumentLoaded(A) {A.trigger("turbo:checkout:iframe:document:loaded");});});\x3c/script\x3e';
if("string"!==typeof a)throw"Attempted to write non-string value to iFrame. typeof \x3d "+typeof a;var b=f();b.open();b.write(a);b.close();p.callAll(e()[0])},remove:function(){e().remove()},appendTo:function(a){h();a.append(k())},insertInto:function(a){h();a.html(k())},hasContent:function(){var a=0<e().length&&f();return a&&(a.body.hasChildNodes()||a.head.hasChildNodes())},registerCallbacks:function(a){m.push(a);p.push(a)},onContentLoaded:g}});"use strict";k.when("A","turbo-checkout-page-ready").register("turbo-checkout-view-state",
function(d){function c(a,b){return function(){return e===a||e===b}}function a(a){return function(){e=a;b.apply(b,arguments)}}function b(a,b){a&&"string"===typeof a&&d.trigger(a,b)}var e=0;return{isClosed:c(0),isClosing:c(1),isOpen:c(2),isOpening:c(3),isClosingOrClosed:c(1,0),isOpeningOrOpen:c(3,2),setToOpen:a(2),setToOpening:a(3),setToClosed:a(0),setToClosing:a(1)}});"use strict";k.when("A","turbo-view-adapter","turbo-checkout-view-state","turbo-checkout-eligible-state","turbo-checkout-content-loader",
"turbo-checkout-utils","turbo-checkout-weblab-allocation","turbo-checkout-weblab-trigger","turbo-checkout-csm","turbo-checkout-state-handler","turbo-checkout-device-filter","turbo-checkout-ajax-wrapper","turbo-checkout-page-visibility-manager","turbo-checkout-counter","turbo-checkout-prefetcher","turbo-checkout-prefetch-timer","turbo-checkout-buy-now-button","turbo-checkout-signin-controller","turbo-checkout-auto-open","turbo-checkout-urls","turbo-checkout-ref-tagger","turbo-configuration","turbo-checkout-event-verification",
"turbo-checkout-page-ready").register("turbo-checkout-controller",function(d,c,a,b,e,f,h,k,g,l,m,p,q,z,w,u,r,A,v,y,x,B,K){function G(){r.bindTurboClickEvent();d.off("turbo:checkout:dimmer:clicked");d.on("turbo:checkout:dimmer:clicked",function(a){a()})}function C(a,b){f.logDebug("turbo-checkout-controller",a,b)}function E(a,b){I();a||c.close({reason:b})}function F(){C("Handling signin success");M()}function L(){C("Handling buy now button click");M();return!0}function M(){W=setTimeout(P,2E4);J=g.createScope();
J.markClick();N="loading";T=!1;u.checkTimeout();z.incrementSheetOpenedCounter();c.show()}function P(){g.logCount("turboCheckoutContenLoadTimeout")}function Q(){I();c.removeContent()}function O(){I();K.logBuyNowButtonClickHandlerMetrics()}function I(){b.canShow()?(C("Registering with buy now button"),d.trigger("turbo:checkout:buyNowEnabled"),r.registerOnClickCallback(L)):(C("Unregistering from buy now button"),d.trigger("turbo:checkout:buyNowDisabled"),r.deregisterOnClickCallback(L))}function S(a,
b){g.logCount("turboCheckoutPrefetchSuccess");a&&(h.isControl()||h.isBuyNowOnly())&&(C("Received content in control: "+a.substring(0,255)),g.logCount("turboCheckoutControlContentReceived"));U=b;c.setContent(a);I()}function R(){I();a.isOpeningOrOpen()&&(g.logCount("turboCheckoutYieldNewPurchase"),c.closeImmediatelyThenExecute(V))}function Y(){clearTimeout(W);N="unknown";!H||H.isResolved()||H.isRejected()||(C("Initiate confirm called for "+U.currentPurchaseId+" with existing confirm still executing. Aborting"),
g.logCount("turboCheckoutConfirmPending"),H._supersedByNewPurchase=!0,H.abort());aa()}function Z(a){var b=0;l.getLineItems().filter(function(a){return a&&a.isDiscoveredAsin}).forEach(function(c,d){a["discoveredAsins."+d]=c.asin;b++});g.logCount("turboCheckoutDiscoveredAsins",b);return a}function aa(){g.logCount("turboCheckoutConfirm");var a=U.currentPurchaseId,b=y.buildConfirmPathWith(l.getRefTag(),h.getExperimentName(),l.getRequestId(),l.getSessionId()),d=Z({pid:a});H=p.loadWithJQXHR(b,{type:"POST",
data:d,success:function(a,b,c){g.logCount("turboCheckoutConfirmSuccess")},error:function(b,d,e){"abort"===d?g.logCount("turboCheckoutConfirmAborted"):("timeout"===d&&g.logCount("turboCheckoutConfirmTimeOut"),g.logCount("turboCheckoutConfirmFailed"));b._supersedByNewPurchase||(f.logError("Issue confirming turbo initiate prefetch for pid "+a+": "+e+", "+d),g.logCount("turboCheckoutYieldNewPurchase"),c.closeImmediatelyThenExecute(V))}})}function ba(){J.markFirstByte()}function V(){r.executeOriginalBuyNowAction(l.getActiveId())}
function ca(a){d.trigger("turbo:checkout:embedded:page:showSpinner");H.done(a)}function ea(a,b,c){N=c;T=!1}function fa(){T=!0}function da(a){d.off("turbo:checkout:dimmer:clicked");d.on("turbo:checkout:dimmer:clicked",function(a){a()});a&&a.doNotLog||(a&&!a.doNotLog?X(N,a.reason):X(N,!1));N="closed"}function X(a,b){var c=y.buildLogPageHitPathWith(T?a+"2":a,b);C("Logging page hit from "+a+" to "+B.get(B.KEYS.HOST_PAGE_TYPE_IDENTIFIER)+" reason "+b);p.load(c,{method:"POST",params:{pageType:B.get(B.KEYS.HOST_PAGE_TYPE_IDENTIFIER),
referrer:a},timeout:4E3})}function ga(){a.isOpeningOrOpen()&&g.logCount("turboCheckoutProductChangedWhileOpening")}var J,N,U,T;x=B.get(B.KEYS.AJAX_PAGE_UPDATE_EVENT);var W,H;d.on(x,G);G();return{pageLoaded:function(){var a=h.getExperimentName();if(a){var f=h.getAllocation();g.addCounterExtraSuffix("wl:"+f);g.addCounterExtraSuffix(a+":"+f)}m.isDeviceTurboEligible()&&(b.setup(),b.registerStateChangeCallback(E),q.setup(),e.registerCallback({onStart:Q,onTurboEligible:O,onFinish:S,onError:R}),k.setup(),
A.setup(),A.registerCallback(F),J=g.createScope(),c.registerCallbacks({beforeFramePopulated:Y,afterFramePopulated:ba}),l.registerCallback(ga),d.on("turbo:checkout:sheet:beforeClose",da),d.on("turbo:checkout:embedded:page:beforeReload",ea),d.on("turbo:checkout:embedded:page:animation:start",fa),v.setup(r.executeTurboBuyNowAction,O),w.setup(),d.trigger("turbo:checkout:controller:onPageLoaded"))},loadFullscreen:function(a,b){function d(){a=f.createFQDN(a);"thankyou"===b?(g.logCount("turboCheckoutYieldTYP"),
c.closeAndNavigate(a)):(g.logCount("turboCheckoutYield"),c.closeToFullscreen(a))}!H||H.isResolved()||H.isRejected()?d():(g.logCount("turboCheckoutWaitYield"),ca(d))},frameContentReady:function(a,b,c){d.trigger("turbo:checkout:embedded:page:ready",a,b);(function(){var a=function(){J.markCriticalFeature();c.confirmHit(B.get(B.KEYS.HOST_PAGE_TYPE_IDENTIFIER),l.getRefTag());J.whenDataSet(c.recordClientSideMetrics);b.off("checkout:afterReload",a)};b.on("checkout:afterReload",a)})();(function(){b.on("checkout:beforeReload",
function(c){d.trigger("turbo:checkout:embedded:page:beforeReload",a,b,c)});b.on("checkout:reload",function(c){d.trigger("turbo:checkout:embedded:page:reload",a,b,c)});b.on("checkout:afterReload",function(c){d.trigger("turbo:checkout:embedded:page:afterReload",a,b,c)});b.on("turbo:checkout:animation:start",function(){d.trigger("turbo:checkout:embedded:page:animation:start")});d.on("turbo:checkout:embedded:page:showSpinner",function(){c.showSpinner()});d.off("turbo:checkout:dimmer:clicked");d.on("turbo:checkout:dimmer:clicked",
function(a){b.trigger("turbo:checkout:dimmer:clicked:iFrame",a)});b.on("turbo:checkout:update:dimmer",function(a){d.trigger("turbo:checkout:update:dimmer:afterReload",a)})})()},frameHtmlRendered:function(){J.markAboveTheFold()},updateBounds:function(a,b){c.updateBounds(a,b)}}});"use strict";k.when("turbo-checkout-page-load-spinner","turbo-checkout-controller","turbo-checkout-csm","turbo-checkout-page-ready").register("turbo-checkout-startup",function(d,c,a){d.removePageLoadSpinner();a.logCount("turboCheckoutControllerPageLoaded");
c.pageLoaded()});"use strict";k.when("turbo-checkout-assets-load-trigger").register("turbo-checkout-page-ready",function(){m.ue&&m.ue.count&&"undefined"!==typeof m.ue_t0&&m.ue.count("turboCheckoutPageReady",Date.now()-m.ue_t0)});"use strict";k.when("A","turbo-checkout-csm","turbo-checkout-utils","turbo-checkout-state-handler","turbo-checkout-quantity-input","turbo-checkout-warranty-input","turbo-checkout-accessories-input","turbo-checkout-page-ready").register("turbo-checkout-authportal-return-query",
function(d,c,a,b,e,f,h){function k(b){a.logDebug("turbo-checkout-authportal-return-query",b)}function g(a){return!!a.match("trb_auth\x3d1")}function l(d){if(g(d)){d=((d||"").match(q)||[])[1]||"";var e=b.getSessionId();a.isNonEmptyString(d)||c.logCount("turboCheckoutPostAuthEmptySessionParameter");a.isNonEmptyString(e)||c.logCount("turboCheckoutPostAuthEmptySessionPageState");a.isNonEmptyString(d)&&a.isNonEmptyString(e)&&d!==e&&(a.logWarning("Turbo Session Flip Detected. Post authentication sessionId \x3d "+
e+", Expected \x3d "+d,"turbo-checkout-authportal-return-query"),c.logCount("turboCheckoutPostAuthSessionFlip"))}}var t=/&?(openid|aToken|serial)[^&]*/g,p=/&?trb_(open|auth|qty|warrAsin|sid|accessory(Asin|Offer))=[^&]*/g,q=/&?trb_sid=([^&]*)/,z=/\?[?&]*/,w=/[?&]{2,}/g;l(m.location.search);return{buildFrom:function(a){k("Initial Query \x3d "+a);a=(a||"?").replace(t,"");a=a.replace(p,"");a+="\x26trb_auth\x3d1\x26trb_open\x3d1";var c=e.getQuantity();a+=1<c?"\x26trb_qty\x3d"+c:"";c=f.getLineItem();a+=
c&&c.asin?"\x26trb_warrAsin\x3d"+c.asin:"";c=b.getSessionId();a+=0<c.length?"\x26trb_sid\x3d"+c:"";c=b.getActiveId();a+=c?"\x26trb_bid\x3d"+c:"";c=h.getLineItem();a+=c&&c.asin&&c.offerListingId?"\x26trb_accessoryAsin\x3d"+c.asin+"\x26trb_accessoryOffer\x3d"+c.offerListingId:"";a=a.replace(z,"?").replace(w,"\x26");k("Final Query \x3d "+a);return a},isReturningFromAuthPortal:g,validateSession:l}});"use strict";k.when("turbo-checkout-utils","turbo-checkout-csm","turbo-checkout-auto-open","turbo-checkout-authportal-return-query",
"turbo-checkout-page-ready").register("turbo-checkout-browser-signin",function(d,c,a,b){function e(a){if(f(a)){c.logCount("turboCheckoutForceMobileClaimCollection");var b=a.match(g)[1],e=decodeURIComponent(b);b===e&&d.logError("The pre-defined returnTo seems to be un-encoded");e=encodeURIComponent(e+(-1===e.indexOf("?")?"?":"\x26")+"openid.return_to\x3d"+h());return a.replace(b,e)}return a+(-1===a.indexOf("?")?"?":"\x26")+"openid.return_to\x3d"+h()}function f(a){return null!==a.match(g)}function h(){var a=
b.buildFrom(m.location.search);return encodeURIComponent("https://"+m.location.hostname+m.location.pathname.replace(t,"/ref\x3dtrb_chk_auth")+a)}function k(){var a=m.location.search.match(l)?"turboCheckoutSigninSuccess":"turboCheckoutSigninFailed";c.logCount(a)}var g=/openid\.return_to=([^&$]+)/,l=/openid\.mode=id_res/,t=/(\/ref=[^/]*\/?$|\/?$)/;b.isReturningFromAuthPortal(m.location.search)&&(c.logCount("turboCheckoutAuthPortalReturn"),k());return{show:function(b){b=e(b);c.logCount("turboCheckoutSignInUrlSize",
b.length);a.reset();m.location.href=b},_encodeSignInUrl:e,_isReturnToParameterPredefined:f}});"use strict";k.when("turbo-checkout-utils","turbo-checkout-state-handler","turbo-checkout-page-ready").register("turbo-checkout-strings",function(d,c){function a(a){return function(){var e=c.getStrings()[a];if(e)return e;d.logDebug("turbo-checkout-strings",'String for key "'+a+'" is undefined! Returning empty string.');return""}}return{getHeaderText:a("TURBO_CHECKOUT_HEADER"),getLoadingText:a("TURBO_LOADING_TEXT")}});
"use strict";k.when("jQuery","turbo-checkout-page-ready").register("turbo-checkout-loading-spinner",function(d){function c(){return d("#turbo-loading-container")}function a(a){var c=d("\x3cdiv\x3e",{id:"turbo-loading-content"}).append(d("\x3cdiv\x3e",{id:"turbo-loading-spinner","class":"a-spinner a-spinner-medium"}));"string"===typeof a&&a&&c.append(d("\x3cdiv\x3e",{id:"turbo-loading-text",text:a}));return c}return{create:function(b){return d("\x3cdiv\x3e",{id:"turbo-loading-container"}).append(a(b))},
get:c,show:function(){c().addClass("turbo-checkout-shown")}}});"use strict";k.when("A","turbo-checkout-utils","turbo-checkout-page-ready").register("turbo-checkout-eligibility-response-weblabs",function(d,c){var a=[];return{set:function(b){d.$.isArray(b)&&(a=b)},get:function(){return a}}});"use strict";k.when("turbo-checkout-csm","turbo-checkout-utils","turbo-checkout-page-ready").register("turbo-checkout-session-storage",function(d,c){function a(a,d){c.logDebug("turbo-checkout-session-storage",a,
d)}return{isPresent:function(b){var c;a:{try{c=m.sessionStorage.getItem(b);break a}catch(f){d.logCount("turboCheckoutSessionStorageExceptionGet"),a("get() exception",f)}c=null}return null!==c&&c!==y},set:function(b,c){try{m.sessionStorage.setItem(b,c)}catch(f){d.logCount("turboCheckoutSessionStorageExceptionSet"),a("set() exception",f)}},remove:function(b){try{return m.sessionStorage.removeItem(b)}catch(c){d.logCount("turboCheckoutSessionStorageExceptionRemove"),a("remove() exception",c)}}}});"use strict";
k.when("A","turbo-configuration","turbo-checkout-page-ready").register("turbo-checkout-load-events",function(d,c){var a=c.get(c.KEYS.AJAX_PAGE_UPDATE_EVENT);return{bind:function(b){d.off(a,b);d.off("turbo:checkout:controller:onPageLoaded",b);d.on(a,b);d.on("turbo:checkout:controller:onPageLoaded",b)}}});"use strict";k.when("A","jQuery","turbo-checkout-csm","turbo-checkout-utils","turbo-checkout-buy-now-button","turbo-configuration","turbo-checkout-page-ready").register("turbo-checkout-event-verification",
function(d,c,a,b,e,f){function h(){var a=f.get(f.KEYS.BUY_NOW_CLICK_EVENT).split(".");return 1<a.length?a[1]:"turboCheckout"}function k(b){var c=b.map(function(a){return a.namespace}).filter(function(a,b,c){return c.indexOf(a)===b});b.length!==c.length&&a.logCount("turboCheckoutBuyNowButtonDuplicateClickHandler")}function g(b){if((b=b.filter(function(a){return a!==y&&"click"===a.type&&0<=p.indexOf(a.namespace)}))&&0<b.length){var c=0;b.forEach(function(b){b.namespace!==h()&&(a.logCount("turboCheckoutBuyNowButtonClickHandlerWhitelisted:"+
b.namespace),c++)});0<c&&a.logCount("turboCheckoutBuyNowButtonClickHandlerWhitelistedQuantity:"+c)}}function l(b){if((b=b.filter(function(a){return a!==y&&"click"===a.type&&0>p.indexOf(a.namespace)}))&&0<b.length){var c=0;b.forEach(function(){a.logCount("turboCheckoutBuyNowButtonClickHandlerNotWhitelisted");c++});a.logCount("turboCheckoutBuyNowButtonClickHandlerNotWhitelistedQuantity:"+c)}}var m=!1,p=[h(),"accessoryUpsellInterstitial","makoPreRegistration","moq","siatc","hctpDFL","bbg","vasBuyNow",
"ppdBundles","makoGiftingMetrics","financialOptionsCheckout"];return{logBuyNowButtonClickHandlerMetrics:function(){var d=e.getBuyNowButtons();if(!m&&d&&0<d.length){for(var f=0;f<d.length;f++){var h=c._data(d[f],"events");if(!h||!h.click){a.logCount("turboCheckoutBuyNowButtonNoBoundHandlers");return}var p=(h=h.click)?h.length:0;1<p&&(b.logDebug("turbo-checkout-event-verification","Multiple handlers bound to 'click' in Buy Now button. Number of handlers: "+p,void 0),a.logCount("turboCheckoutBuyNowButtonMultipleClickEventsBound"),
a.logCount("turboCheckoutBuyNowButtonMultipleClickEventsBoundQuantity:"+p));k(h);l(h);g(h)}m=!0}}}})});
/* ******** */
(function(f){var p=window.AmazonUIPageJS||window.P,q=p._namespace||p.attributeErrors,a=q?q("TurboCheckoutDesktopAssets",""):p;a.guardFatal?a.guardFatal(f)(a,window):a.execute(function(){f(a,window)})})(function(f,p,q){f.when("turbo-configuration-keys","turbo-checkout-page-ready").register("turbo-device-configuration",function(a){var c;c||(c={},c[a.SHOW_SIGN_IN_INTERFACE]="turbo-checkout-browser-signin",c[a.EXTEND_ELIGIBLE_STATE]=!1,c[a.IS_DEVICE_FILTER_REQUIRED]=!0,c[a.VIEW_ADAPTER]="turbo-checkout-modal",
c[a.WARRANTY_CHECKBOX_INPUT_SELECTOR]="input[id^\x3dmbb-offeringID-]",c[a.WARRANTY_CHECKBOX_RELATIVE_PARENT_SELECTOR]=".abbListItem",c[a.WARRANTY_OFFER_INPUT_SELECTOR]="input[id^\x3dmbb-offeringID-]:checked",c[a.WARRANTY_ASIN_INPUT_NAME]="asin");return c});"use strict";f.when("A","turbo-checkout-csm","turbo-checkout-utils","turbo-configuration","turbo-checkout-device-variant","turbo-checkout-is-touch-and-orientation-enabled","turbo-checkout-page-ready").register("turbo-checkout-device-filter",function(a,
c,k,f,g,p){function h(a){var b=!1;this.countOnce=function(){b||(c.logCount(a),b=!0)}}function d(a){k.logDebug("turbo-checkout-device-filter",a)}var q="turboCheckoutDisabledDesktopAuiVariant"+g,l,b,u,v,r,m,w;return{isDeviceTurboEligible:function(){l=l||new h("Desktop"===g?"turboCheckoutDesktopAuiVariantEligible":q);var e;(e=b)||(e=k.isInternetExplorer()?"turboCheckoutDisabledDesktopIE":k.isIPad()?"turboCheckoutDisabledDesktopIPad":k.isIPhone()?"turboCheckoutDisabledDesktopIPhone":k.isAndroid()?"turboCheckoutDisabledDesktopAndroid":
"turboCheckoutDesktopUserAgentEligible",e=new h(e));b=e;u=u||new h("turboCheckoutDisabledDesktopTouch");v=v||new h("turboCheckoutDisabledDesktopOrientation");r=r||new h("turboCheckoutDisabledDesktopTouchAndOrientation");m=m||new h("turboCheckoutDisabledTurboDesktopOnDevice");w=w||new h("turboCheckoutEnabledTurboDesktopOnDevice");l.countOnce();"Desktop"===g||d("Aui device variant is NOT Desktop. Turbo will NOT show. Variant is "+g);(e="Desktop"!==g)||(b.countOnce(),e=!!(k.isInternetExplorer()||k.isIPad()||
k.isAndroid()||k.isIPhone()));if(e)return m.countOnce(),!1;if(e=a.capabilities.touch)u.countOnce(),d("Touch enabled device. Turbo will NOT show");var c=a.capabilities.orientation;c&&(v.countOnce(),d("Orientation enabled device. Turbo will NOT show"));e&&c&&r.countOnce();if((e||c)&&!p)return m.countOnce(),!1;w.countOnce();return!0},isSignInSupported:function(){return f.get(f.KEYS.IS_SIGN_IN_SUPPORTED)}}});"use strict";f.when("turbo-checkout-page-ready").execute(function(){f.declare("turbo-checkout-device-variant",
"Desktop")});"use strict";f.when("A","a-modal","turbo-checkout-csm","turbo-checkout-utils","turbo-checkout-iframe","turbo-checkout-base-view","turbo-checkout-loading-spinner","turbo-checkout-view-state","turbo-checkout-ref-tagger","turbo-checkout-strings","turbo-checkout-page-ready").register("turbo-checkout-modal",function(a,c,f,E,g,F,h,d,z,l){function b(a){E.logDebug("turbo-checkout-modal",a)}function u(){!A()||d.isOpeningOrOpen()?b("show() suppressed. View is null or undefined or view state is opening or open"):
(d.setToOpening(),m().show())}function v(){x&&d.isOpeningOrOpen()&&(g.appendTo(e()),g.write(x))}function r(){g.remove();if(0<e().length)b("Modal frame is in DOM. Inserting Spinner"),e().height("").html(h.create(l.getLoadingText())).append(w()),t("#turbo-checkout-modal-header").text(l.getHeaderText());else{b("Modal frame is NOT in DOM. Resetting Modal");var a={inlineContent:t("\x3cdiv\x3e",{id:"turbo-checkout-frame"}).html(h.create(l.getLoadingText())).append(w()).prop("outerHTML"),padding:"none",
dataStrategy:"inline",header:'\x3cdiv id\x3d"turbo-checkout-modal-header"\x3e'+l.getHeaderText()+"\x3c/div\x3e"};m().update(a)}}function m(){return B=B||c.get(t("#turbo-checkout-modal"))}function w(){return t("\x3cscript/\x3e",{type:"text/javascript",html:'P.when("A").execute(function turboFrameReady(A) { A.trigger("turbo:checkout:frame:ready"); });'})}function e(){return t("#turbo-checkout-frame")}function y(a){!A()||d.isClosingOrClosed()?b("close() suppressed. View is undefined or null or view state is closing or closed"):
(n=a||n,n.notify=!0===n.notify||n.notify===q,d.setToClosing(),m().hide())}function A(){var a=m();a||b("Modal is undefined or null. Modal \x3d "+a);return a?!0:!1}function C(b){t(document.body).unbind("click");b();a.trigger("turbo:checkout:sheet:onNavigateAway");y({notify:!1,immediate:!0,doNotLog:!0})}function D(a){b("onDismiss");n={notify:!0,reason:a}}var t=a.$,n={},x,B,G=new (F.extend())("#turbo-checkout-frame");g.onContentLoaded(function(a){h.get().remove()});a.on("a:popover:dismiss:turbo",function(){b("onClick_X");
D(z.TAGS.TOUCH_X)});a.declarative("a-popover-floating-close","click",function(){b("onDimmerClicked");D(z.TAGS.TOUCH)});a.on("a:popover:beforeShow:turbo",function(){b("onBeforeOpen");d.setToOpening("turbo:checkout:sheet:beforeOpen");r()});a.on("a:popover:show:turbo",function(){b("onOpen");d.setToOpen();x||h.show()});a.on("a:popover:beforeHide:turbo",function(){b("onBeforeClose");d.setToClosing.apply(d,!0===n.notify?["turbo:checkout:sheet:beforeClose",n]:q);e().removeClass("turbo-checkout-shown")});
a.on("a:popover:hide:turbo",function(){b("onClose");d.setToClosed("turbo:checkout:sheet:afterClose");n={}});a.on("a:popover:afterHide:turbo",r);a.on("turbo:checkout:sheet:doOpen",u);a.on("turbo:checkout:sheet:doClose",y);a.on("turbo:checkout:frame:ready",v);a.on(a.constants.BROWSER_EVENTS.ORIENTATION_CHANGE,function(){f.logCount("turboCheckoutDesktopOrientationChange");d.isOpen()&&f.logCount("turboCheckoutDesktopOrientationChangeWhenModalOpen")});a.on("turbo:checkout:state:product:resolved",function(){t("#turbo-checkout-modal-header").text(l.getHeaderText())});
return{show:u,setContent:function(a){x=a;b("iFrame content saved");d.isOpeningOrOpen()?v():(b("setFrameContent NOT called"),b("viewState is not opening? isOpeningOrOpen \x3d "+d.isOpeningOrOpen()),b("iFrame already has content? iFrame.hasContent \x3d "+g.hasContent()))},removeContent:function(){x="";r()},close:y,closeToFullscreen:function(a){C(function(){p.location.href=a})},closeImmediatelyThenExecute:C,closeAndNavigate:function(b){p.location.href=b;a.trigger("turbo:checkout:sheet:onNavigateAway");
y({notify:!1,doNotLog:!0})},registerCallbacks:g.registerCallbacks,updateBounds:function(a){G.updateBounds(a)}}});"use strict";f.declare("turbo-checkout-is-touch-and-orientation-enabled",!1)});
/* ******** */
(function(c){var d=window.AmazonUIPageJS||window.P,e=d._namespace||d.attributeErrors,a=e?e("DetailPageTurboCheckoutDesktopAssets",""):d;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,d,e){c.when("turbo-configuration-keys","turbo-checkout-page-ready").register("turbo-client-configuration",function(a){var b;b||(b={},b[a.HOST_PAGE_TYPE_IDENTIFIER]="detail",b[a.BUY_NOW_ONLY_TREATMENT]="T1",b[a.NO_PREFETCH_TREATMENT]=/T[2-9]/,b[a.ADDRESS_INPUT_SELECTORS]=["#unifiedLocation1ClickAddress",
"#addToCart input[name\x3d'dropdown-selection']","#unifiedLocationAddress","input[name\x3d'dropdown-selection']"],b[a.QUANTITY_SELECT_SELECTOR]="#quantity",b[a.CONFLICTING_INITIATE_LISTENERS]=["click.siatc"],b[a.VAS_CHANGE_EVENTS]=["vas:remove-service-asin-buybox-event","vas:add-service-asin-buybox-event"],b[a.VAS_CHECKBOX_SELCTOR]="#ppdb-add-service-checkbox");return b})});
/* ******** */
